"""genesis/catalog.py -- the COMPLETE built-in-category graphic-style
catalog (the object-styles table) generated by OUR discipline scheme over
the Revit 2026 graphic-category ENUM -- the K6-FAIL branch of the reader
bisection ("the un-referenced built-in-category style catalog is
required" => our base must carry a GStyleElem row for EVERY category the
reader can look up, not just the 46 our house standard styles).

THE ENUM IS A FORMAT CONSTANT, THE VALUES ARE OURS.  Every reader-accepted
Revit 2026 project carries object-style rows for the SAME set of built-in
category ids: **1,074 categories, each with exactly one projection style,
333 of them also with a cut style, IDENTICAL across every sample** (proven
by :func:`derive_builtin_category_enum` on rst / rme / rac -- the id set
and the cuttable subset agree to the id; see
``experiments/genesis/singletons/builtin_category_enum.json``).  That set
+ cuttability is the release's REGISTERED GRAPHIC-CATEGORY ENUM (like the
public ``BuiltInCategory`` API enum it extends with the built-in
sub-categories) -- an interface constant we may enumerate.  What each row
CARRIES (pen weights, colour, line pattern, material) is a document's
graphic standard = expression: OUR values come from the discipline scheme
of ``rvt.genesis.house_standard`` (pens / colour by discipline) applied by
OUR classification RULES below.  Autodesk's per-category default pen /
colour VALUES (the quarantined 1,074-row table under
``experiments/genesis/reference/``) are never read here: the assayer will
diff our rows against them, and value identity beyond the format
constants (ids, style type, screen-sized flag) would be a defect.

FIXER v2 (2026-08-03): the table is SHAPED per (category, type) by the
frozen structural PROFILE (:data:`PROFILE_FILE`, derived by
:func:`derive_builtin_style_profile`): each key's ElementHeader flag word
(the low byte is a per-CATEGORY compiled-in property), its pattern / pen
NULL cells, its screen-sized flag and its built-in material id are format
constants the six samples agree on -- the earlier uniform-shape table put
2,560 fields outside the per-key observed sets (the fixer's linter,
:func:`lint_builtin_style_catalog`, now reads 0 hard findings).  Colours
and pen VALUES stay ours.

Territory: this module + ``rvt.genesis.settings``.  Imports the proven
GStyleElem / CategoryElem constructors of the types stream unchanged.
"""
from __future__ import annotations

import collections
import json
import os
import sys
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from .types import (TypeRecord, IdArg, INVALID, LINEPATTERN_SOLID, new_gstyle,
                    _alloc)

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
#: the frozen enum record (my territory: experiments/genesis/singletons/)
ENUM_FILE = os.path.join(ROOT, "experiments", "genesis", "singletons",
                         "builtin_category_enum.json")

#: samples the enum is derived from (any accepted 2026 project agrees;
#: three suffice to prove sample-independence)
DERIVE_SAMPLES = ("rstbasicsampleproject", "rmebasicsampleproject",
                  "racbasicsampleproject")


# ---------------------------------------------------------------------------
# 1. the enum: derive once from the corpus, freeze, load
# ---------------------------------------------------------------------------

def _load_sample_documents(samples: Sequence[str]):
    """Yield ``(sample, Document)`` for each research-corpus sample -- the
    ONE place this module reads the corpus (the documented format-constant
    derivations below; nothing at generation time)."""
    from ..mutate import Document
    for s in samples:
        yield s, Document.load(s)


def derive_builtin_category_enum(samples: Sequence[str] = DERIVE_SAMPLES,
                                 verbose: bool = True) -> dict:
    """Derive the graphic-category ENUM: every built-in (negative) category
    id that carries a non-family-scoped object-style GStyleElem row in the
    HOST document of each sample, with the style TYPES present (1 =
    projection, 2 = cut).  Asserts the id set and the per-id type set are
    IDENTICAL across ``samples`` (else it is not a format constant) and
    returns {"categories": [{"id", "cut"}], ...}."""
    per_sample: Dict[str, Dict[int, set]] = {}
    for s, doc in _load_sample_documents(samples):
        rows: Dict[int, set] = collections.defaultdict(set)
        for gid in doc.ids_of_class("GStyleElem", host_only=True):
            v = doc.value(gid) or {}
            if v.get("m_famId", -1) != -1:            # family-scoped rows: content
                continue
            cid = v.get("m_categoryId")
            if isinstance(cid, int) and cid < 0:
                rows[cid].add(int(v.get("m_gstyleType", 1)))
        per_sample[s] = dict(rows)
        if verbose:
            print(f"   [enum] {s}: {len(rows)} built-in categories, "
                  f"{sum(1 for t in rows.values() if 2 in t)} cuttable")
    base = None
    for s, rows in per_sample.items():
        norm = {k: tuple(sorted(v)) for k, v in rows.items()}
        if base is None:
            base = norm
        elif norm != base:
            diff_ids = set(norm) ^ set(base)
            raise RuntimeError(f"graphic-category enum differs in {s}: "
                               f"{len(diff_ids)} ids differ (not a format constant?)")
    assert base is not None
    cats = [{"id": int(cid), "cut": 2 in ts} for cid, ts in sorted(base.items())]
    return {
        "generator": "rvt.genesis.catalog.derive_builtin_category_enum",
        "derived_from": list(per_sample),
        "note": ("The Revit-2026 graphic-category ENUM: every built-in category id "
                 "carrying an object-style row, plus its cuttability -- IDENTICAL "
                 "in every sample (a per-release registered constant, like the public "
                 "BuiltInCategory enum). Only ids and the cut flag are recorded: NO "
                 "pen / colour / pattern VALUE is read from any sample."),
        "count": len(cats),
        "cuttable": sum(1 for c in cats if c["cut"]),
        "categories": cats,
    }


def load_builtin_category_enum(path: str = ENUM_FILE, *,
                               derive_if_missing: bool = True) -> dict:
    """Load the frozen enum (derive + freeze it on first use)."""
    if os.path.exists(path):
        with open(path) as fh:
            return json.load(fh)
    if not derive_if_missing:
        raise FileNotFoundError(path)
    enum = derive_builtin_category_enum()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(enum, fh, indent=1)
    return enum


# ---------------------------------------------------------------------------
# 1b. the per-key STRUCTURAL PROFILE of the object-styles table (fixer v2)
# ---------------------------------------------------------------------------
#: The object-styles table is NOT "1,407 identical-shape rows differing
#: only in pen / colour": each (category, style-type) key has a STRUCTURAL
#: profile every reader-accepted 2026 file agrees on (the six-sample
#: linter run, 2026-08-03, 8,442 built-in host rows):
#:
#:  * the ElementHeader flag word ``m_abFlags4Bytes`` LOW BYTE is per-KEY
#:    (bit 0x10 constant across all six files for 1,352 of 1,407 keys; the
#:    modal split is 679 keys 0x0E / 728 keys 0x1E) -- our uniform 0x1E
#:    preset put ~679 categories' flag byte outside their observed set;
#:  * 380 keys carry ``m_linePatternId`` == -1 (NO pattern cell) in every
#:    file; 30 always carry one specific non-solid BUILT-IN pattern id;
#:    165 always carry a document pattern element (document wiring);
#:  * 40 keys carry pen 0 / -1 (NO pen cell) in every file;
#:  * 48 keys are ``m_isScreenSized`` == True in every file (0 keys mixed);
#:  * 32 keys carry a BUILT-IN material id (-4000010, -4000031..-4000052) in
#:    every file; 27 always carry a document material (the row is WIRED to a
#:    material element -- a document-wiring input, not a value we invent).
#:
#: These are compiled-in properties of the built-in category (interface
#: constants like the enum ids / cuttability / pen count), NOT authored
#: expression: pens / colours (the value-bearing fields) stay OURS.  The
#: profile is derived once from the corpus, frozen next to the fixer's
#: rungs, and applied by :func:`builtin_style_catalog`.
PROFILE_FILE = os.path.join(ROOT, "experiments", "genesis", "subst_v2",
                            "builtin_style_profile.json")

#: the built-in SOLID line pattern (LinePatternElem id -3000010)
BUILTIN_SOLID_PATTERN = LINEPATTERN_SOLID
#: header flag bit set exactly on rows that CARRY a CellList (racbasic /
#: rstbasic era); our rows carry NO CellList, so it must be clear
AB_CELLLIST_BIT = 0x800


def _modal(counter: "collections.Counter"):
    return counter.most_common(1)[0][0] if counter else None


def derive_builtin_style_profile(samples: Sequence[str] = None,
                                 verbose: bool = True) -> dict:
    """Derive, per (category id, style type) key of the built-in
    object-styles table, the STRUCTURAL profile the six samples agree on:
    the header flag word (modal, cell-list era bit cleared), the visible-
    view flags, the pattern rule ('null' | 'solid' | 'builtin:<id>' |
    'elem'), the material rule ('null' | 'builtin:<id>' | 'elem'), the
    screen-sized flag, the pen rule ('ours' | 'null0' | 'nullneg1') + the
    observed pen range.  Only STRUCTURE / format constants are recorded --
    no colour, and pen VALUES only as an observed range for the linter."""
    samples = list(samples or ("rstbasicsampleproject", "rmebasicsampleproject",
                               "racbasicsampleproject", "racadvancedsampleproject",
                               "rstadvancedsampleproject", "dach-sample-project"))
    per: Dict[Tuple[int, int], dict] = collections.defaultdict(lambda: {
        "ab": collections.Counter(), "vis": collections.Counter(),
        "pat_val": collections.Counter(), "pat_kind": collections.Counter(),
        "mat_val": collections.Counter(), "mat_kind": collections.Counter(),
        "scr": collections.Counter(), "pen": collections.Counter(),
        "files": set()})
    n_rows = 0
    for s, doc in _load_sample_documents(samples):
        seen = 0
        for gid in doc.ids_of_class("GStyleElem", host_only=True):
            v = doc.value(gid) or {}
            if v.get("m_famId", -1) != -1 or v.get("m_ownerId", -1) != -1:
                continue                                   # family / owner scoped
            cid = v.get("m_categoryId")
            if not (isinstance(cid, int) and cid < 0):
                continue                                   # project subcategory rows
            gt = int(v.get("m_gstyleType", 1))
            key = (int(cid), gt)
            p = per[key]
            p["files"].add(s)
            gs = ((v.get("m_pGStyle") or {}).get("value") or {})
            pat = gs.get("m_linePatternId")
            mat = gs.get("m_materialElemId")
            pen = gs.get("m_penNumber")
            p["pat_kind"]["null" if pat == INVALID else
                          ("builtin" if isinstance(pat, int) and pat < 0 else "elem")] += 1
            if isinstance(pat, int) and pat < 0 and pat != INVALID:
                p["pat_val"][int(pat)] += 1
            p["mat_kind"]["null" if mat == INVALID else
                          ("builtin" if isinstance(mat, int) and mat < 0 else "elem")] += 1
            if isinstance(mat, int) and mat < 0 and mat != INVALID:
                p["mat_val"][int(mat)] += 1
            p["scr"][bool(gs.get("m_isScreenSized"))] += 1
            if isinstance(pen, int):
                p["pen"][int(pen)] += 1
            h = doc.decode(gid, 101)
            if h and getattr(h, "clean", False) and h.value:
                p["ab"][int(h.value.get("m_abFlags4Bytes") or 0)] += 1
                p["vis"][int(((h.value.get("m_viewRules") or {})
                                 .get("m_nVisibleViewFlags") or 0))] += 1
            seen += 1
        n_rows += seen
        if verbose:
            print(f"   [profile] {s}: {seen} built-in object-style rows")
    keys = {}
    for (cid, gt), p in sorted(per.items()):
        # --- header flags: modal value among rows WITHOUT the cell-list era
        # bit (we emit no CellList); else the modal with that bit cleared
        clean = collections.Counter({a: c for a, c in p["ab"].items()
                                     if not (a & AB_CELLLIST_BIT)})
        ab = _modal(clean)
        if ab is None:
            ab = (_modal(p["ab"]) or 0) & ~AB_CELLLIST_BIT
        vis = _modal(p["vis"])
        # --- pattern rule (STRICT rules only when EVERY observation agrees)
        kinds = set(p["pat_kind"])
        if kinds == {"null"}:
            pattern = "null"                               # no pattern cell, ever
        elif kinds == {"elem"}:
            pattern = "elem"                               # always a document pattern
        elif "builtin" in kinds:
            if BUILTIN_SOLID_PATTERN in p["pat_val"]:
                pattern = "solid"                          # solid observed -> ours
            elif kinds == {"builtin"}:
                pattern = f"builtin:{_modal(p['pat_val'])}"   # one built-in id, always
            else:
                pattern = "solid"                          # mixed; solid family in-set kind
        else:
            pattern = "nullwire"                           # mixed null / element: null default
        # --- material rule
        mkinds = set(p["mat_kind"])
        if mkinds == {"null"}:
            material = "null"
        elif mkinds == {"elem"}:
            material = "elem"                              # always a document material
        elif mkinds == {"builtin"}:
            material = f"builtin:{_modal(p['mat_val'])}"      # one built-in id, always
        else:
            material = "nullwire"                          # null in-set: our default
        # --- screen-sized flag: True only when EVERY observation is True
        screen = (set(p["scr"]) == {True})
        # --- pen rule: null only when EVERY observation is the null pen
        pens = set(p["pen"])
        if pens == {0}:
            pen_rule = "null0"
        elif pens == {-1}:
            pen_rule = "nullneg1"
        else:
            pen_rule = "ours"
        keys[f"{cid}:{gt}"] = {
            "cat": cid, "type": gt, "files": len(p["files"]),
            "ab": int(ab), "ab_set": sorted(int(x) for x in p["ab"]),
            "vis": int(vis) if vis is not None else -32768,
            "pattern": pattern, "pattern_kinds": dict(p["pat_kind"]),
            "pattern_builtin_ids": sorted(int(x) for x in p["pat_val"]),
            "material": material, "material_kinds": dict(p["mat_kind"]),
            "material_builtin_ids": sorted(int(x) for x in p["mat_val"]),
            "screen_sized": bool(screen),
            "pen": pen_rule,
            "pen_min": (min(pens) if pens else None),
            "pen_max": (max(pens) if pens else None),
        }
    rules = collections.Counter(k["pattern"] for k in keys.values())
    mats = collections.Counter(k["material"] for k in keys.values())
    return {
        "generator": "rvt.genesis.catalog.derive_builtin_style_profile",
        "derived_from": samples, "rows_analysed": n_rows, "count": len(keys),
        "note": ("Per (built-in category, style type) STRUCTURAL profile the six "
                 "reader-accepted samples agree on: modal ElementHeader flag word "
                 "(low byte is per-category; cell-list era bit cleared), visible-"
                 "view flags, pattern rule (null / solid / one built-in pattern / "
                 "document-wired), material rule (null / built-in id / document-"
                 "wired), the screen-sized flag and the pen-null rule + observed pen "
                 "range.  STRUCTURE ONLY: no colour and no authored value is recorded."),
        "summary": {"pattern_rules": dict(rules), "material_rules": dict(mats),
                    "screen_sized_keys": sum(1 for k in keys.values() if k["screen_sized"]),
                    "pen_null_keys": sum(1 for k in keys.values() if k["pen"] != "ours"),
                    "ab_low_bytes": dict(collections.Counter(
                        f"0x{k['ab'] & 0xFF:02X}" for k in keys.values()))},
        "keys": keys,
    }


def load_builtin_style_profile(path: str = PROFILE_FILE, *,
                               derive_if_missing: bool = True) -> dict:
    """Load the frozen per-key structural profile (derive + freeze on first use)."""
    if os.path.exists(path):
        with open(path) as fh:
            return json.load(fh)
    if not derive_if_missing:
        raise FileNotFoundError(path)
    prof = derive_builtin_style_profile()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(prof, fh, indent=1)
    return prof


# ---------------------------------------------------------------------------
# 2. OUR classification RULES: category id -> discipline
# ---------------------------------------------------------------------------
#: The BuiltInCategory id space is allocated in decade BANDS by domain
#: (observed on the enum: -2000xxx architectural / annotation core,
#: -2001xxx model & site categories, -2002xxx detailing / mass / area,
#: -2003xxx information & analysis surfaces, -2004xxx dimension /
#: annotation styles, -2005xxx tags, -2006xxx datum heads & symbols,
#: -2007xxx connectors, -2008xxx MEP curves & devices, -2009xxx structural
#: & analytical, -2010xxx fabrication / systems analysis).  OUR RULE
#: colours a category by its band (the discipline it belongs to), except
#: the categories our house standard names explicitly (walls, ducts,
#: conduits ...), which take their listed discipline.  This is OUR
#: documented graphic-standard rule -- a mechanical classification, not
#: a copied per-category table.
BAND_DISCIPLINE: List[Tuple[int, int, str]] = [
    (-2001000, -2000000, "architectural"),   # walls/doors/windows/floors/stairs/lines
    (-2002000, -2001000, "architectural"),   # equipment, site, structure, links
    (-2003000, -2002000, "annotation"),      # detail items, area/mass surfaces
    (-2004000, -2003000, "general"),         # analysis / information categories
    (-2006000, -2004000, "annotation"),      # dimension styles, tags
    (-2007000, -2006000, "annotation"),      # datum heads, callouts, revisions
    (-2008000, -2007000, "electrical"),      # connectors
    (-2009000, -2008000, "mechanical"),      # MEP curves & devices (see refinements)
    (-2010000, -2009000, "structural"),      # structural / analytical
    (-2011000, -2010000, "general"),         # fabrication, systems analysis
]

#: refinements inside the MEP band (-2008xxx): piping vs electrical
#: sub-ranges of the enum [ids per the public BuiltInCategory allocation:
#: 20080xx ducts / duct devices; 200804x-200806x pipes & plumbing;
#: 200807x-200814x electrical devices, wire, cable tray, conduit].
def _mep_subdiscipline(cat_id: int) -> str:
    n = -cat_id - 2008000          # 0..999 within the MEP band
    if 40 <= n <= 69:
        return "piping"
    if 70 <= n <= 144:
        return "electrical"
    return "mechanical"


def _explicit_disciplines() -> Dict[int, str]:
    """Categories our house standard classifies explicitly (its
    HOUSE_CATEGORIES table) -- these override the band rule."""
    from . import house_standard as hs
    return {int(cid): disc for cid, _lbl, disc, _cut in hs.HOUSE_CATEGORIES}


#: OUR INK: the catalog's neutral line-work colour is a rich near-black
#: (RGB 24,24,24), not pure #000000 -- a common CAD/plot-standard choice
#: (our "layer black") that also makes every catalog row OURS by value:
#: Autodesk's per-category defaults use pure black hairlines for hundreds
#: of categories, and a (pen 1, #000000, solid) row would be value-identical
#: to theirs with no expression on either side.  Pure black stays reserved
#: for the house standard's own 46 named categories (hs.HOUSE_CATEGORIES
#: rows, built by the house standard, not by this generator).
INK_BLACK = 0x181818                       # COLORREF r|g<<8|b<<16 (grey => symmetric)


def catalog_scheme() -> Dict[str, Tuple[int, int, int]]:
    """OUR CATALOG colour scheme = the house discipline scheme
    (``house_standard.HOUSE_SCHEME``: discipline -> (projection pen, cut
    pen, colour)) with the neutral disciplines' pure black replaced by
    :data:`INK_BLACK` for the generated (non-house) categories."""
    from . import house_standard as hs
    out = {}
    for disc, (ppen, cpen, col) in hs.HOUSE_SCHEME.items():
        out[disc] = (int(ppen), int(cpen), INK_BLACK if int(col) == 0 else int(col))
    return out


def classify_category(cat_id: int, explicit: Optional[Dict[int, str]] = None) -> str:
    """OUR discipline for a built-in category id (rule: explicit house
    classification, else the MEP sub-range, else the id BAND)."""
    exp = explicit if explicit is not None else _explicit_disciplines()
    if cat_id in exp:
        return exp[cat_id]
    if -2009000 < cat_id <= -2008000:
        return _mep_subdiscipline(cat_id)
    for lo, hi, disc in BAND_DISCIPLINE:
        if lo < cat_id <= hi:
            return disc
    return "general"


# ---------------------------------------------------------------------------
# 3. the catalog generator
# ---------------------------------------------------------------------------

def _profile_key(cat_id: int, gtype: int) -> str:
    return f"{int(cat_id)}:{int(gtype)}"


def _apply_row_profile(rec: TypeRecord, prof: Optional[dict]) -> None:
    """Stamp the per-category ElementHeader flag word onto the row's
    seq-101 header (the low byte is a per-category compiled-in property;
    the cell-list era bit is never set -- our rows carry no CellList) and
    record the profile in ``refs`` for the linter."""
    if not prof:
        return
    ab = int(prof.get("ab") or 0) & ~AB_CELLLIST_BIT
    if ab:
        rec.header["m_abFlags4Bytes"] = ab
    vis = prof.get("vis")
    if vis is not None:
        (rec.header.get("m_viewRules") or {})["m_nVisibleViewFlags"] = int(vis)
    rec.refs["profile"] = {k: prof.get(k) for k in
                           ("ab", "pattern", "material", "screen_sized", "pen")}


def _resolve_pattern(prof: Optional[dict], wired: Optional[int],
                     default: int) -> Tuple[int, Optional[str]]:
    """(pattern id, note) for a row: the profile's STRICT rule first
    ('null' = no cell / 'builtin:<id>' = the one built-in pattern the key
    always carries / 'elem' = always a document pattern -> the caller's
    ``wiring``), else OUR default (solid) or the null default for the
    mixed 'nullwire' keys.  Wiring is honoured ONLY on strict 'elem' keys:
    everywhere else the pattern is OUR graphic choice."""
    rule = (prof or {}).get("pattern", "solid")
    if rule == "null":
        return INVALID, None
    if rule == "nullwire":
        return INVALID, None                              # null is in-set: our default
    if isinstance(rule, str) and rule.startswith("builtin:"):
        return int(rule.split(":", 1)[1]), None
    if rule == "elem":
        if wired is not None and int(wired) not in (0, INVALID):
            return int(wired), None
        return int(default), "pattern:elem-key without wiring (default solid)"
    return int(default), None                              # 'solid'


def _resolve_material(prof: Optional[dict], wired: Optional[int],
                      default: int) -> Tuple[int, Optional[str]]:
    """(material id, note): the strict rule ('null' / 'builtin:<id>' /
    'elem' -> ``wiring``); 'nullwire' and unknown -> OUR default (-1)."""
    rule = (prof or {}).get("material", "null")
    if rule in ("null", "nullwire"):
        return INVALID, None
    if isinstance(rule, str) and rule.startswith("builtin:"):
        return int(rule.split(":", 1)[1]), None
    if rule == "elem":
        if wired is not None and int(wired) not in (0, INVALID):
            return int(wired), None
        return int(default), "material:elem-key without wiring (default -1)"
    return int(default), None


def _resolve_pen(prof: Optional[dict], ours: int) -> int:
    rule = (prof or {}).get("pen", "ours")
    if rule == "null0":
        return 0
    if rule == "nullneg1":
        return -1
    return int(ours)


def builtin_style_catalog(ids: IdArg, *,
                          enum: Optional[dict] = None,
                          exclude_categories: Iterable[int] = (),
                          material_id: int = INVALID,
                          line_pattern_id: int = LINEPATTERN_SOLID,
                          scheme: Optional[Dict[str, Tuple[int, int, int]]] = None,
                          profile: Optional[dict] = None,
                          use_profile: bool = True,
                          wiring: Optional[Dict[Tuple[int, int], dict]] = None,
                          id_map: Optional[Dict[Tuple[int, int], int]] = None,
                          ) -> List[TypeRecord]:
    """The COMPLETE built-in-category object-styles table: one projection
    ``GStyleElem`` per enum category + one cut ``GStyleElem`` per CUTTABLE
    category, coloured / weighted by OUR discipline scheme
    (``house_standard.HOUSE_SCHEME``: discipline -> (projection pen, cut
    pen, colour)) and SHAPED by the per-key structural profile
    (:data:`PROFILE_FILE`): per-category header flag word, the pattern /
    pen null cells, the screen-sized flag and the built-in material ids
    (format constants), plus optional document ``wiring`` = ``{(category,
    type): {'material_id', 'line_pattern_id'}}`` for the keys the profile
    marks 'elem' (their material / pattern is a reference to a document
    element the caller owns -- the substitution rung passes the parent's).
    ``exclude_categories`` = categories the base document already styles
    (e.g. the 46 house-standard categories in G1_candidate) so the catalog
    COMPLETES the base instead of duplicating rows.  ``id_map`` =
    ``{(category, type): element id}`` pins rows to EXISTING ids (the
    in-place substitution probe: the row is rebuilt AT the id it already
    occupies).  ``use_profile=False`` reproduces the pre-fixer (uniform-
    shape) output for A/B probes.  Returns [TypeRecord, ...] (header key
    'GStyleElem:objectstyle')."""
    enum = enum or load_builtin_category_enum()
    prof_all = ((profile if profile is not None else load_builtin_style_profile())
                if use_profile else {"keys": {}})
    pkeys = prof_all.get("keys", {})
    sch = scheme or catalog_scheme()
    explicit = _explicit_disciplines()
    skip = set(int(c) for c in exclude_categories)
    wiring = wiring or {}
    id_map = id_map or {}
    out: List[TypeRecord] = []
    for row in enum["categories"]:
        cid = int(row["id"])
        if cid in skip:
            continue
        disc = classify_category(cid, explicit)
        ppen, cpen, colour = sch.get(disc, sch.get("general", (1, 3, 0)))
        for gtype, our_pen in ((1, ppen), (2, cpen)):
            if gtype == 2 and not row.get("cut"):
                continue
            prof = pkeys.get(_profile_key(cid, gtype)) if use_profile else None
            wired = wiring.get((cid, gtype)) or {}
            pat, pnote = _resolve_pattern(prof, wired.get("line_pattern_id"),
                                          line_pattern_id)
            mat, mnote = _resolve_material(prof, wired.get("material_id"), material_id)
            pen = _resolve_pen(prof, our_pen)
            screen = bool(prof.get("screen_sized")) if prof else False
            fixed_id = id_map.get((cid, gtype))
            rec = new_gstyle(cid, style_type=("cut" if gtype == 2 else "projection"),
                             pen=int(pen), color=int(colour), line_pattern_id=int(pat),
                             material_id=int(mat), screen_sized=screen,
                             ids=(None if fixed_id is not None else ids),
                             elem_id=(int(fixed_id) if fixed_id is not None else None))
            _apply_row_profile(rec, prof)
            rec.refs["discipline"] = disc
            for note in (pnote, mnote):
                if note:
                    rec.notes.append(note)
            out.append(rec)
    return out


def lint_builtin_style_catalog(records: Sequence[TypeRecord],
                               profile: Optional[dict] = None,
                               *, standalone: bool = True) -> dict:
    """The fixer's specimen LINT for the object-styles table: diff every
    row against the frozen per-key structural profile.  Hard findings =
    format-constant violations (header flag byte, pattern / pen null cells,
    screen-sized flag, built-in material id, gstyle type / owner / family
    shape); soft = document-wiring inputs left at their standalone
    defaults ('elem' keys with no wiring -- resolved by the substitution
    rung's parent wiring).  Returns {'hard': [...], 'soft': [...], 'rows':
    n, 'ok': hard == 0}."""
    prof_all = profile if profile is not None else load_builtin_style_profile()
    pkeys = prof_all.get("keys", {})
    hard: List[dict] = []
    soft: List[dict] = []
    seen_keys = set()
    for r in records:
        v = r.obj
        cid = int(v.get("m_categoryId"))
        gt = int(v.get("m_gstyleType"))
        key = _profile_key(cid, gt)
        seen_keys.add(key)
        prof = pkeys.get(key)
        gs = ((v.get("m_pGStyle") or {}).get("value") or {})
        hdr = r.header

        def bad(what, ours, want):
            hard.append({"id": r.elem_id, "key": key, "field": what,
                         "ours": ours, "expected": want})
        # universal shape
        if v.get("m_ownerId") != INVALID:
            bad("m_ownerId", v.get("m_ownerId"), INVALID)
        if v.get("m_famId") != INVALID:
            bad("m_famId", v.get("m_famId"), INVALID)
        if v.get("m_designOptionId") != INVALID:
            bad("m_designOptionId", v.get("m_designOptionId"), INVALID)
        if v.get("m_cellList") is not None:
            bad("m_cellList", "present", None)
        if hdr.get("m_categroryId") != INVALID:
            bad("hdr.m_categroryId", hdr.get("m_categroryId"), INVALID)
        if hdr.get("m_familyId") != INVALID:
            bad("hdr.m_familyId", hdr.get("m_familyId"), INVALID)
        if prof is None:
            hard.append({"id": r.elem_id, "key": key, "field": "key",
                         "ours": key, "expected": "a registered (category, type) key"})
            continue
        # per-key structural profile
        ab = int(hdr.get("m_abFlags4Bytes") or 0)
        want_ab = int(prof["ab"]) & ~AB_CELLLIST_BIT
        if (ab & 0xFF) != (want_ab & 0xFF):
            bad("hdr.m_abFlags4Bytes(low byte)", hex(ab), hex(want_ab))
        if ab & AB_CELLLIST_BIT:
            bad("hdr.m_abFlags4Bytes(cell-list bit)", hex(ab), "clear (no CellList)")
        if ab not in prof.get("ab_set", []) and ab != want_ab:
            bad("hdr.m_abFlags4Bytes(value)", hex(ab), [hex(x) for x in prof.get("ab_set", [])])
        vis = int(((hdr.get("m_viewRules") or {}).get("m_nVisibleViewFlags") or 0))
        if vis != int(prof.get("vis", -32768)):
            bad("hdr.m_nVisibleViewFlags", vis, prof.get("vis"))
        pat = gs.get("m_linePatternId")
        rule = prof.get("pattern")
        pat_ids = set(prof.get("pattern_builtin_ids") or [])
        if rule == "null" and pat != INVALID:
            bad("m_linePatternId", pat, "-1 (no pattern cell on this key)")
        elif isinstance(rule, str) and rule.startswith("builtin:") and pat != int(rule.split(":", 1)[1]):
            bad("m_linePatternId", pat, rule)
        elif rule == "elem" and (not isinstance(pat, int) or pat < 1):
            (soft if standalone else hard).append(
                {"id": r.elem_id, "key": key, "field": "m_linePatternId",
                 "ours": pat, "expected": "document-wired pattern element"})
        elif rule == "solid" and isinstance(pat, int) and pat < 0 and pat != INVALID \
                and pat not in pat_ids and pat != BUILTIN_SOLID_PATTERN:
            bad("m_linePatternId(builtin id)", pat, sorted(pat_ids))
        elif rule == "nullwire" and isinstance(pat, int) and pat < 0 and pat != INVALID:
            bad("m_linePatternId", pat, "-1 or a document pattern (nullwire key)")
        mat = gs.get("m_materialElemId")
        mrule = prof.get("material")
        if mrule == "null" and mat != INVALID:
            bad("m_materialElemId", mat, "-1")
        elif isinstance(mrule, str) and mrule.startswith("builtin:") and mat != int(mrule.split(":", 1)[1]):
            bad("m_materialElemId", mat, mrule)
        elif mrule == "elem" and (not isinstance(mat, int) or mat < 1):
            (soft if standalone else hard).append(
                {"id": r.elem_id, "key": key, "field": "m_materialElemId",
                 "ours": mat, "expected": "document-wired material element"})
        elif mrule == "nullwire" and isinstance(mat, int) and mat < 0 and mat != INVALID:
            bad("m_materialElemId", mat, "-1 or a document material (nullwire key)")
        if bool(gs.get("m_isScreenSized")) != bool(prof.get("screen_sized")):
            bad("m_isScreenSized", gs.get("m_isScreenSized"), prof.get("screen_sized"))
        pen = gs.get("m_penNumber")
        prule = prof.get("pen")
        if prule == "null0" and pen != 0:
            bad("m_penNumber", pen, 0)
        elif prule == "nullneg1" and pen != -1:
            bad("m_penNumber", pen, -1)
        elif prule == "ours":
            lo, hi = prof.get("pen_min"), prof.get("pen_max")
            if isinstance(pen, int) and pen == 0 and (lo is None or lo > 0):
                bad("m_penNumber", pen, "a real pen (key never carries the null pen)")
    return {"rows": len(records), "keys": len(seen_keys),
            "hard": hard, "soft": soft, "ok": not hard}


def catalog_report(records: Sequence[TypeRecord]) -> dict:
    """Counts per discipline / style type for the record + a round-trip
    proof over the whole catalog."""
    by_disc = collections.Counter(r.refs.get("discipline", "?") for r in records)
    by_type = collections.Counter(r.refs.get("style_type") for r in records)
    ok = 0
    fails = []
    for r in records:
        rep = r.roundtrip()
        if rep["ok"]:
            ok += 1
        else:
            fails.append({"elem_id": r.elem_id, "report": rep})
    return {"rows": len(records), "roundtrip_ok": ok,
            "by_discipline": dict(by_disc.most_common()),
            "by_style_type": {("projection" if k == 1 else "cut" if k == 2 else str(k)): v
                              for k, v in by_type.items()},
            "failures": fails[:5]}


# ---------------------------------------------------------------------------
# DEMO / self-test
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    from .types import IdSource
    if "--derive" in argv or not os.path.exists(ENUM_FILE):
        enum = derive_builtin_category_enum()
        os.makedirs(os.path.dirname(ENUM_FILE), exist_ok=True)
        with open(ENUM_FILE, "w") as fh:
            json.dump(enum, fh, indent=1)
        print(f"enum frozen -> {os.path.relpath(ENUM_FILE, ROOT)}: "
              f"{enum['count']} categories, {enum['cuttable']} cuttable")
    else:
        enum = load_builtin_category_enum()
        print(f"enum loaded: {enum['count']} categories, {enum['cuttable']} cuttable")
    if "--derive-profile" in argv or not os.path.exists(PROFILE_FILE):
        prof = derive_builtin_style_profile()
        os.makedirs(os.path.dirname(PROFILE_FILE), exist_ok=True)
        with open(PROFILE_FILE, "w") as fh:
            json.dump(prof, fh, indent=1)
        print(f"style profile frozen -> {os.path.relpath(PROFILE_FILE, ROOT)}: "
              f"{prof['count']} keys, summary {prof['summary']}")
    src = IdSource(2_000_000)
    recs = builtin_style_catalog(src, enum=enum)
    rep = catalog_report(recs)
    print(f"complete built-in style catalog: {rep['rows']} GStyleElem rows "
          f"(round-trip clean+byte-exact {rep['roundtrip_ok']}/{rep['rows']})")
    print("   by discipline:", rep["by_discipline"])
    print("   by style type:", rep["by_style_type"])
    for f in rep["failures"]:
        print("   FAIL", f)
    lint = lint_builtin_style_catalog(recs)
    print(f"   specimen lint: hard {len(lint['hard'])}, soft (document-wiring) "
          f"{len(lint['soft'])}, ok {lint['ok']}")
    return 0 if (rep["roundtrip_ok"] == rep["rows"] and lint["ok"]) else 1


if __name__ == "__main__":
    sys.exit(main())
