"""rvt.convert.rfa_load -- the standalone-born .rfa LOAD lane (issue #99).

Fresh-clone runnable (no samples/, no ifcopenshell): OUR own panelboard
.rfa is generated by rvt.famgen.factory at start_id=1000 (standalone-born
by construction) and loaded onto the pinned, plugin-bundled genesis base
through the schema-typed id remap + rvt.famload; then the same file goes
through the product router (`rfa -> rvt`) for the default release and for
--target-version 2025.

What is asserted is what OUR gates can prove -- project validator 0
errors, four-registry census coherent, the loaded family present in all
four registries, the id law honoured.  Autodesk's reader is the arbiter of
"loads" (rule 4): the MECHANISM is certified as T2a in the ledger, these
artifacts are not, and the route says so.
"""
from __future__ import annotations

import json
import os
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from rvt.convert import rfa_load as RL                     # noqa: E402
from rvt.frontdoor import router as R                      # noqa: E402


def _pinned_base(target=None):
    try:
        from rvt.frontdoor.base import resolve_base
        return resolve_base(target_release=target).path
    except Exception:
        return None


PINNED_BASE = _pinned_base()
PINNED_2025 = _pinned_base(2025)
needs_pin = pytest.mark.skipif(PINNED_BASE is None, reason="pinned genesis base absent")
needs_pin_2025 = pytest.mark.skipif(PINNED_2025 is None,
                                    reason="pinned 2025 genesis base absent")


def _catalog_ok() -> bool:
    try:
        from rvt.famgen import factory as F
        F.resolve_panelboard_facts("eaton", "pow-r-line", mains_a=400, spaces=42,
                                   voltage="480Y/277", mcb=True, mounting="surface",
                                   panel_name="X")
        return True
    except Exception:
        return False


needs_catalog = pytest.mark.skipif(not _catalog_ok(), reason="famgen catalog absent")


@pytest.fixture(scope="module")
def panel_rfa(tmp_path_factory):
    """OUR generated panelboard .rfa (start_id=1000, family-mode VALID)."""
    if not _catalog_ok():
        pytest.skip("famgen catalog absent")
    from rvt.famgen import factory as F
    out = tmp_path_factory.mktemp("rfa") / "DP-1.rfa"
    prod = F.make_panelboard(vendor="eaton", line="pow-r-line", mains_a=400,
                            spaces=42, voltage="480Y/277", mcb=False,
                            mounting="surface", panel_name="DP-1")
    rep = prod.write(str(out), validate=True)
    assert rep["ok"], rep
    return str(out)


def _validator_errors(path: str) -> int:
    from rvt import validate as V
    vr = V.validate_file(path)
    return sum(1 for f in vr.findings if f.severity == V.SEV_ERROR)


# ---------------------------------------------------------------------------
# the reader + the id law
# ---------------------------------------------------------------------------

@needs_catalog
@needs_pin
def test_our_rfa_is_standalone_born_against_the_pinned_base(panel_rfa):
    born, floor, wm = RL.is_standalone_born(panel_rfa, PINNED_BASE)
    assert born is True
    assert floor == 1000 and wm > 1_000_000, (floor, wm)


@needs_catalog
def test_source_facts_and_typed_remap_build(panel_rfa):
    """RfaSource reads the file once (owners from Global/ElemTable, its own
    schema) and builds a rebased document at any start_id: contiguous block,
    self-Family first, every ElementId-typed value remapped, owner ids
    remapped alongside, GElement reps kept."""
    src = RL.RfaSource(panel_rfa)
    f = src.facts
    assert f.n_units == 1 and f.n_elements >= 30
    assert f.id_floor == 1000 and f.self_family == 1000
    assert f.category == -2001040                       # OST_ElectricalEquipment
    assert f.real_type_names and all(n.strip() for n in f.real_type_names)
    assert f.owner_source == "Global/ElemTable"
    assert f.class_histogram.get("Family") == 1
    doc = src.build(start_id=2_000_001)
    ids = sorted(e.elem_id for e in doc.elements)
    assert ids[0] == 2_000_001 and ids == list(range(ids[0], ids[0] + len(ids)))
    assert doc.self_family.elem_id == 2_000_001
    assert doc.finalized and doc.category_id == f.category
    assert [n for n, _ in doc.types] == f.real_type_names
    census = src.builds[-1]
    assert census["mode"] == "schema-typed decode-time remap"
    assert census["ids_remapped_values"] > len(ids)      # m_id + m_famId at least
    # no element keeps a reference into the OLD id block (1000..1000+n)
    old = set(src.members)
    owners = {e.owner_id for e in doc.elements if e.owner_id > 0}
    assert owners and owners.isdisjoint(old) and owners <= set(ids)
    for e in doc.elements:
        assert e.obj.get("m_id") in (None, e.elem_id)
        fid = e.obj.get("m_famId")
        assert fid is None or fid < 0 or fid in ids
    assert any(e.rep for e in doc.elements)               # GElement reps carried
    # a second build lands in its own block (the loader may call it again)
    doc2 = src.build(start_id=3_000_001)
    assert min(e.elem_id for e in doc2.elements) == 3_000_001
    assert doc2.document_guid != doc.document_guid        # a fresh content GUID per load
    unit = doc.to_embedded_unit()
    assert unit["record_count"] == len(ids) and set(unit["segments"]) == {101, 102, 103}


@needs_catalog
def test_graveyard_footer_is_refused_by_name(panel_rfa, tmp_path, monkeypatch):
    """A GraveyardRec-carrying ElemTable (never observed; codec gap #13) is a
    named refusal, not a guess and not a traceback from deep inside."""
    real = RL._elemtable

    def fake(path):
        et = real(path)
        et.footer.graveyard_count = 3
        return et
    monkeypatch.setattr(RL, "_elemtable", fake)
    with pytest.raises(RL.RfaLoadError) as ei:
        RL.RfaSource(panel_rfa)
    assert "GraveyardRec" in str(ei.value) and "#13" in str(ei.value)


def test_missing_file_is_a_named_refusal(tmp_path):
    with pytest.raises(RL.RfaLoadError):
        RL.RfaSource(str(tmp_path / "nope.rfa"))


@needs_pin
def test_a_project_passed_as_rfa_is_refused_by_name(tmp_path):
    """A .rvt is not a family: refused up front (no PartAtom manifest), in
    one line, before any decode is attempted; the route relays it."""
    import shutil
    with pytest.raises(RL.RfaLoadError) as ei:
        RL.RfaSource(PINNED_BASE)
    assert "not a family file" in str(ei.value)
    fake = str(tmp_path / "a_project.rfa")
    shutil.copyfile(PINNED_BASE, fake)
    res = R.route({"rfa": fake, "rvt": PINNED_BASE}, "rvt", out=str(tmp_path / "o"))
    assert res.ok is False and "not a family file" in res.line
    assert "Closest supported routes" in res.line
    assert "loaded_rvt" not in res.files


# ---------------------------------------------------------------------------
# the load (module) and the route (product CLI surface)
# ---------------------------------------------------------------------------

@needs_catalog
@needs_pin
def test_load_our_rfa_onto_the_pinned_base_validates_zero_errors(panel_rfa, tmp_path):
    from rvt.famload import four_registry_census
    out = str(tmp_path / "DP-1_loaded.rvt")
    rec = RL.load_rfa_into_project(panel_rfa, PINNED_BASE, out)
    assert rec["ok"] is True, rec
    assert os.path.isfile(out) and os.path.isfile(out + ".load.json")
    assert rec["validate"]["verdict"] == "VALID" and rec["validate"]["n_errors"] == 0
    assert rec["registries"]["coherent"] is True and rec["registries"]["ours_in_all_four"] is True
    assert rec["family_inventory_ok"] is True
    wm = rec["host_watermark"]
    assert rec["rebase"]["start_id"] == wm + 1                     # T2a's allocation law
    lo, hi = rec["ids"]["doc_id_range"]
    assert lo == wm + 1 and rec["ids"]["host_family"] == hi + 1
    assert rec["ids"]["twins"] == 14                                # one twin per family parameter
    # independent gates on the written file
    assert _validator_errors(out) == 0
    census = four_registry_census(out)
    assert census["coherent"] is True and census["save_units"] == 2


@needs_catalog
@needs_pin
def test_route_rfa_to_rvt_loads_our_standalone_born_rfa(panel_rfa, tmp_path):
    """THE flipped cell (issue #99): `route run --output rvt --rfa ours.rfa`
    delivers a loaded project instead of the clear line."""
    res = R.route({"rfa": panel_rfa}, "rvt", out=str(tmp_path / "o"))
    assert res.ok is True, res.errors + [res.status, res.line]
    assert res.route == "rfa_load" and res.line == ""
    stages = [s["stage"] for s in res.steps]
    assert stages == ["rfa-classify", "rfa-born-load"], stages
    assert "id-remap lane" in res.status and "VALID 0 errors" in res.status
    loaded = res.files["loaded_rvt"]
    assert os.path.isfile(loaded) and os.path.isfile(res.files["load_report"])
    assert _validator_errors(loaded) == 0
    cav = " ".join(res.caveats)
    assert "STANDALONE-BORN" in cav and RL.CERTIFIED_BY in cav
    assert "THIS artifact is not" in cav                            # never "loads in Revit"
    man = json.load(open(res.manifest_paths["route.json"]))
    assert man["ok"] is True and man["files"]["loaded_rvt"]


@needs_catalog
@needs_pin_2025
def test_route_rfa_to_rvt_target_2025_loads_onto_the_2025_base(panel_rfa, tmp_path):
    """--target-version 2025 with no --rvt: the default host becomes the
    certified 2025 base and the load runs under that release."""
    from rvt import versions as V
    res = R.route({"rfa": panel_rfa}, "rvt", out=str(tmp_path / "o"), target_version=2025)
    assert res.ok is True, res.errors + [res.status, res.line]
    assert (res.target_version or {}).get("status") == "match"
    loaded = res.files["loaded_rvt"]
    assert V.detect_release(loaded) == 2025
    assert res.releases.get("loaded_rvt") == 2025
    assert _validator_errors(loaded) == 0


@needs_catalog
@needs_pin
def test_target_version_is_ignored_with_an_explicit_host(panel_rfa, tmp_path):
    res = R.route({"rfa": panel_rfa, "rvt": PINNED_BASE}, "rvt", out=str(tmp_path / "o"),
                  target_version=2025)
    assert res.ok is True, res.errors + [res.status]
    assert any("ignored for the LOAD" in c for c in res.caveats)


def test_matrix_names_the_new_lane_and_keeps_its_evidence_honest():
    from rvt.frontdoor import matrix as M
    for key in ((("rfa",), "rvt"), (("rfa", "rvt"), "rvt")):
        cell = M.CELLS[M.key_for(*key)]
        assert "rfa-born-load" in cell.stages and "rfa-classify" in cell.stages
        assert any("rvt.convert.rfa_load" in c and "needs-viewer" in c for c in cell.caveats)
    assert M.STAGES["rfa-born-load"].impl == "rvt.convert.rfa_load:load_rfa_into_project"
    # hard problems only: a certified binary absent on disk is the expected
    # fresh-clone state (experiments/**/*.rvt are git-ignored), soft-marked
    problems = [p for p in M.verify_evidence()
                if M.ABSENT_BINARY_MARK not in p
                and ("rfa_load" in p or "rfa-born" in p or "rfa-classify" in p)]
    assert problems == [], problems
