"""tekton-ifc report.py describes the file it delivers (issue #760): with
harden.json it renders the HARDENED file's own validation report -- `--after`,
or the validate-after.json beside harden.json when that is the report of the
file harden.json produced (same path, score and size) -- and names both files
in its first line; without an after-report it stays on the input, says so,
and warns.  Synthetic
validation reports, stdlib only (fresh-clone safe).
"""
from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys

import pytest
from test_ifc_flow_754 import FILES, SCRIPTS

REPORT = os.path.join(SCRIPTS, "report.py")


def _rep(path: str, score: float, tier: str, *, products: list, tessellated: int = 0,
         phantoms: int = 0, size: int = 1000, fixes: list | None = None) -> dict:
    """The subset of a validate_ifc.py report that report.render() reads."""
    n = len(products)
    return {
        "file": path, "file_size": size, "engine_version": "test",
        "schema": {"schema": "IFC4", "n_errors": 0},
        "score": {"score": score, "tier": tier, "top_fixes": fixes or [],
                  "stats": {"products": n, "tessellated": tessellated,
                            "tessellated_fraction": (tessellated / n) if n else 0.0,
                            "identity_placements": tessellated}},
        "types": {"type_objects": 1},
        "phantoms": {"count": phantoms,
                     "findings": [{"class": "IfcBuildingElementProxy", "name": "clearance", "confidence": "high",
                                   "reasons": ["named like a clearance zone"]}][:phantoms]},
        "spatial": {"storey_count": 1, "space_count": 0},
        "psets": {"pset_names": ["Pset_Panel"], "typing_smells": [], "inconsistent": []},
        "products": products,
    }


def _product(name: str, kind: str) -> dict:
    return {"name": name, "class": "IfcElectricDistributionBoard", "revit_category": "Electrical Equipment",
            "geometry": {"kinds": [kind]}}


BEFORE = _rep("/in/electrical-room.ifc", 35.7, "Tier 0 (v1-like) -- frozen",
              products=[_product("DP-1", "tessellated"), _product("DP-2", "tessellated")],
              tessellated=2, phantoms=1, size=686804,
              fixes=[{"component": "geometry", "fix": "harden_ifc.py converts the boxes"}])
AFTER = _rep("/out/hardened.ifc", 77.0, "Tier 1 (partial) -- usable",
             products=[_product("DP-1", "swept"), _product("DP-2", "tessellated")],
             tessellated=1, phantoms=0, size=996653)
HARDEN = {"output": "/out/hardened.ifc",
          "before": {"score": 35.7, "tier": "Tier 0 (v1-like) -- frozen", "elements": 2, "tessellated_elements": 2},
          "after": {"score": 77.0, "tier": "Tier 1 (partial) -- usable", "elements": 2, "tessellated_elements": 1,
                    "size_bytes": 996653},
          "actions": {"boxes_converted": 1, "phantoms_removed": 1}}
HARDENED_TITLE = "# Revit-readiness report: `hardened.ifc` (hardened from `electrical-room.ifc`)"


@pytest.fixture(scope="module")
def report():
    """report.py imported from its path (stdlib-only; no engine modules)."""
    spec = importlib.util.spec_from_file_location("report_under_test", REPORT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture
def out(tmp_path):
    """validate.json + harden.json + validate-after.json under the names
    ifc_flow.py and the documented four-call path write them."""
    d = tmp_path / "out"
    d.mkdir()
    for role, obj in (("validate", BEFORE), ("harden", HARDEN), ("validate_after", AFTER)):
        (d / FILES[role]).write_text(json.dumps(obj))
    return d


def _cli(report, capsys, *argv):
    """report.main(argv) in-process: (exit code, stderr)."""
    rc = report.main([str(a) for a in argv])
    return rc, capsys.readouterr().err


def test_single_report_describes_that_file_as_before(report):
    md = report.render(BEFORE)
    assert md.splitlines()[0] == "# Revit-readiness report: `electrical-room.ifc`"
    assert "**Score: 35.7/100** — **Tier 0 (v1-like) -- frozen**" in md
    assert "## Before / after hardening" not in md
    assert "| DP-1 | IfcElectricDistributionBoard | Electrical Equipment | triangle mesh |" in md
    assert md.endswith("_Generated by tekton-ifc test from `electrical-room.ifc`._")


def test_the_hardened_file_is_the_subject_when_its_report_is_rendered(report):
    md = report.render(AFTER, HARDEN, source="electrical-room.ifc")
    assert md.splitlines()[0] == HARDENED_TITLE
    assert "**Score: 77.0/100** — **Tier 1 (partial) -- usable**" in md      # the delivered file's verdict
    assert "**Score: 35.7/100**" not in md                                   # the input's is the before column only
    assert "| score | 35.7 | 77.0 |" in md and "| tier | Tier 0 (v1-like) -- frozen | Tier 1 (partial) -- usable |" in md
    assert "- 2 model elements; 1 triangle-mesh (50% tessellated), 1 without a real insertion point" in md
    assert "- File size 996,653 bytes" in md
    assert "| DP-1 | IfcElectricDistributionBoard | Electrical Equipment | clean solid |" in md   # the hardened geometry
    assert "## Phantom solids" not in md                                     # removed by hardening: none left to report
    assert "None — this file is already Tier 1." in md                       # the hardened file's remaining fixes
    assert md.endswith("_Generated by tekton-ifc test from `electrical-room.ifc`, delivered as `hardened.ifc`._")


def test_hardened_file_with_schema_errors_is_still_reported_errors_first(report):
    bad = dict(AFTER, schema={"schema": "IFC4", "n_errors": 3})
    body = report.render(bad, HARDEN, source="electrical-room.ifc").splitlines()
    assert body[0] == HARDENED_TITLE
    assert body[4] == "- IFC schema `IFC4` — **3 schema error(s) — must be fixed first**"   # first bullet under the headline
    assert "| score | 35.7 | 77.0 |" in body


def test_cli_finds_the_after_report_beside_harden_json(report, out, tmp_path, capsys):
    """The documented command -- no --after -- describes the hardened file
    because the flow's validate-after.json sits beside harden.json."""
    md_path = tmp_path / "delivery-report.md"
    assert _cli(report, capsys, out / FILES["validate"], "--compare", out / FILES["harden"], "-o", md_path) == (0, "")
    md = md_path.read_text()
    assert md.splitlines()[0] == HARDENED_TITLE
    # explicit --after names the same file: same bytes
    md2 = tmp_path / "explicit.md"
    rc, _ = _cli(report, capsys, out / FILES["validate"], "--compare", out / FILES["harden"],
                 "--after", out / FILES["validate_after"], "-o", md2)
    assert rc == 0 and md2.read_text() == md


STALE = {
    "no-after-report": None,
    "unreadable-sibling": "{not json",
    "not-a-report": "[1]",
    "another-output": json.dumps(dict(AFTER, file="/out/hardened-v1.ifc")),
    "same-path-earlier-run": json.dumps(dict(AFTER, score=dict(AFTER["score"], score=47.5), file_size=1108684)),
}


@pytest.mark.parametrize("stale", list(STALE), ids=list(STALE))
def test_cli_without_the_hardened_files_report_stays_on_the_input_and_says_so(report, out, tmp_path, capsys, stale):
    """No validate-after.json, an unreadable one, or one left by an EARLIER
    hardening run (another output file, or the same path with other numbers
    than harden.json records): the input is reported, never withheld."""
    if STALE[stale] is None:
        (out / FILES["validate_after"]).unlink()
    else:
        (out / FILES["validate_after"]).write_text(STALE[stale])
    md_path = tmp_path / "delivery-report.md"
    rc, err = _cli(report, capsys, out / FILES["validate"], "--compare", out / FILES["harden"], "-o", md_path)
    assert rc == 0
    assert err.startswith("warning: no report of the hardened file (") and err.endswith(
        "); the report describes the input -- pass --after validate-after.json\n")
    assert {"no-after-report": "no validate-after.json beside harden.json", "unreadable-sibling": "unreadable",
            "not-a-report": "unreadable: ",
            "another-output": "is not the report of /out/hardened.ifc",
            "same-path-earlier-run": "is not the report of /out/hardened.ifc"}[stale] in err
    md = md_path.read_text()
    assert md.splitlines()[0] == "# Revit-readiness report: `electrical-room.ifc` (the input, before hardening)"
    assert "**Score: 35.7/100**" in md and "| score | 35.7 | 77.0 |" in md


def test_cli_single_file_is_unchanged(report, out, tmp_path, capsys):
    assert _cli(report, capsys, out / FILES["validate"], "-o", tmp_path / "r.md") == (0, "")
    assert (tmp_path / "r.md").read_text().splitlines()[0] == "# Revit-readiness report: `electrical-room.ifc`"


def test_cli_explicit_after_is_the_operators_assertion(report, out, tmp_path, capsys):
    """--after is taken as given (the bench renames its artifacts) -- except
    an unreadable file, or the input's own report, which are usage errors."""
    (out / "moved.json").write_text(json.dumps(dict(AFTER, file="/elsewhere/renamed.ifc")))
    md_path = tmp_path / "r.md"
    assert _cli(report, capsys, out / FILES["validate"], "--compare", out / FILES["harden"],
                "--after", out / "moved.json", "-o", md_path) == (0, "")
    assert md_path.read_text().splitlines()[0] == "# Revit-readiness report: `renamed.ifc` (hardened from `electrical-room.ifc`)"
    for bad in ("{not json", "[1]", '{"file": "/out/x.ifc"}'):
        (out / "bad.json").write_text(bad)
        rc, err = _cli(report, capsys, out / FILES["validate"], "--compare", out / FILES["harden"],
                       "--after", out / "bad.json", "-o", tmp_path / "r2.md")
        assert rc == 2 and err.startswith("error: ") and not (tmp_path / "r2.md").exists(), bad
    rc, err = _cli(report, capsys, out / FILES["validate"], "--compare", out / FILES["harden"],
                   "--after", out / FILES["validate"], "-o", tmp_path / "r3.md")
    assert rc == 2 and "is the report of the input itself" in err and not (tmp_path / "r3.md").exists()


def test_script_entry_point(out, tmp_path):
    """One real launch: the __main__ shim and the printed `report -> ...` line."""
    p = subprocess.run([sys.executable, REPORT, str(out / FILES["validate"]), "--compare", str(out / FILES["harden"]),
                        "-o", str(tmp_path / "r.md")], capture_output=True, text=True, timeout=60)
    assert (p.returncode, p.stderr, p.stdout) == (0, "", f"report -> {tmp_path / 'r.md'}\n")
    assert (tmp_path / "r.md").read_text().splitlines()[0] == HARDENED_TITLE
