"""Tests for rvt.famgen.famdoc_adoc -- FAMILY-GENESIS: the family-level
ADocument codec + the retired partition unit footer / stream end record.

Evidence tiers:

1. THE FOOTER GRAMMAR (counsel C5): the decoded 10-byte universal end record
   constant, the universal "Data generated by ..." signature string, and
   OUR unit-footer blob (deterministic 64-byte nonce / the proven empty
   form); the corpus proof (``footer_forensics``) on the family archetype.
2. THE FAMILY ADocument: ``author_family_adocument`` in every mode
   (candidate / purity / minimal) decodes clean, round-trips, carries
   ZERO dangling element ids (schema census), ZERO donor element ids
   (independent byte scan), ZERO donor / employee name strings, indexes
   exactly OUR elements, names OUR self-Family as the owner.
3. THE CLEAN EMISSION: ``emit_family_rfa_v2`` writes a container that reads
   back clean, validates with 0 errors in family mode, and passes the
   byte-level ``provenance_scan_v2`` (footer ours, end record = the decoded
   constant, no donor footer/parity, identity ours).

Corpus-dependent tests skip when the archetype ``.rfa`` / schema are absent.
The samples-corpus footer forensics are exercised on the archetype only
(the full six-project sweep is the deliverable's ``footer_forensics.json``).
"""
from __future__ import annotations

import os
import struct

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RFA = os.path.join(ROOT, "vendor", "phi-ag-rvt", "examples", "Autodesk",
                   "racbasicsamplefamily-2026.rfa")
GA_TOOL = os.path.join(ROOT, "tools", "genesis_assemble.py")
HAVE_RFA = os.path.exists(RFA)
HAVE_TOOL = os.path.exists(GA_TOOL)

from rvt.famgen import famdoc_adoc as FA                    # noqa: E402

needs_rfa = pytest.mark.skipif(not HAVE_RFA, reason="archetype .rfa absent")
needs_stack = pytest.mark.skipif(not (HAVE_RFA and HAVE_TOOL),
                                 reason="archetype .rfa or genesis-2 assembler absent")


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def s0e_doc():
    """The geometry-free electrical family (fast: 25 elements)."""
    from rvt.famgen import skeleton as fs
    return fs.build_s0e_electrical()


@pytest.fixture(scope="module")
def panel_doc():
    """The flagship product: the Eaton panel (geometry + connector + params)."""
    from rvt.famgen import factory as F
    return F.make_panelboard(vendor="eaton", line="pow-r-line", mains_a=400,
                            spaces=42, voltage="480Y/277", mcb=True,
                            mounting="surface").doc


# ---------------------------------------------------------------------------
# 1. the footer / end-record grammar
# ---------------------------------------------------------------------------

def test_end_record_is_the_decoded_10_byte_constant():
    assert FA.FAMILY_END_RECORD == bytes.fromhex("a30300000000ffffffff")
    tag, a, b = struct.unpack("<Hii", FA.FAMILY_END_RECORD)
    assert (tag, a, b) == (0x3A3, 0, -1)
    assert len(FA.FAMILY_END_RECORD) == 10


def test_signature_string_wire_form():
    assert FA.DATA_GENERATED_STRING == "Data generated by Autodesk® Revit®"
    n = struct.unpack_from("<I", FA.FOOTER_STRING_BYTES, 0)[0]
    assert n == len(FA.DATA_GENERATED_STRING) == 34
    assert FA.FOOTER_STRING_BYTES[4:] == FA.DATA_GENERATED_STRING.encode("utf-16-le")
    assert len(FA.FOOTER_STRING_BYTES) == 4 + 68


def test_signature_matches_the_writer_constant():
    # the string this stream classifies is the SAME constant the writer emits
    from rvt.famgen import skeleton as fs
    assert fs.DATA_GENERATED_STRING == FA.DATA_GENERATED_STRING


def test_build_footer_nonce_shape_and_determinism():
    b1 = FA.build_footer(guid="11111111-2222-3333-4444-555555555555", payload=b"abc")
    b2 = FA.build_footer(guid="11111111-2222-3333-4444-555555555555", payload=b"abc")
    b3 = FA.build_footer(guid="11111111-2222-3333-4444-555555555555", payload=b"abd")
    b4 = FA.build_footer(guid="99999999-2222-3333-4444-555555555555", payload=b"abc")
    assert len(b1) == FA.FOOTER_BLOB_LEN == 64
    assert b1 == b2                      # deterministic
    assert b1 != b3 and b1 != b4         # depends on payload + guid


def test_build_footer_empty_form_and_bad_mode():
    assert FA.build_footer(mode="empty") == b""
    with pytest.raises(ValueError):
        FA.build_footer(mode="checksum")


def test_footer_wire_layout():
    blob = b"\xaa" * 64
    wire = FA.footer_wire(blob)
    assert wire[:2] == struct.pack("<H", 0x0F28)          # terminator tag
    assert wire[2:18] == b"\x00" * 16
    tag, n = struct.unpack_from("<HI", wire, 18)
    assert tag == 0x0F3F and n == 64
    assert wire[24:88] == blob
    assert wire.endswith(FA.FOOTER_STRING_BYTES)


def test_footer_tokens_classify_every_region():
    kinds = {v["status"] for v in FA.FOOTER_TOKENS.values()}
    assert kinds == {"format", "ours", "retired"}
    assert FA.FOOTER_TOKENS["footer_string"]["status"] == "format"
    assert FA.FOOTER_TOKENS["footer_blob_bytes"]["status"] == "ours"
    assert FA.FOOTER_TOKENS["end_record_donor_parity"]["status"] == "retired"


@needs_rfa
def test_footer_forensics_on_the_archetype():
    """The corpus proof on the archetype alone: signature present, blob 64 B,
    the true end record is the constant, unframe/reframe byte-exact, and the
    depaged 'tail' is the raw file's own final-block parity."""
    rep = FA.footer_forensics(files=[RFA], with_digest_tests=True)
    assert rep["units"] >= 1
    assert rep["string"]["universal"] is True
    assert rep["string"]["occurrences"].get(FA.DATA_GENERATED_STRING) == 1
    assert rep["blob"]["lengths"].get(64) == 1
    assert rep["blob"]["digest_tests"]["matches"] == []
    ends = rep["end_record"]["streams"]
    assert len(ends) == 1
    e = ends[0]
    assert e["true_end_record"] == FA.FAMILY_END_RECORD.hex()
    assert e["true_end_record_is_constant"] is True
    assert e["unframe_reframe_byte_exact"] is True
    # the depaged walker's "end record" carried extra bytes = the final
    # block's CRCIO parity (framing, not content)
    assert e["walker_end_record_len"] > len(FA.FAMILY_END_RECORD)
    assert e["junk_is_raw_final_block_parity"] is True


# ---------------------------------------------------------------------------
# 2. the family ADocument
# ---------------------------------------------------------------------------

@needs_rfa
def test_template_is_the_family_shape():
    tree, meta = FA.family_template_tree()
    assert meta["roundtrip_exact"] is True
    assert meta["appinfo_slots"] == 239                # family-editor slot table
    assert meta["owner_family_id"] > 0                 # a family document has an owner
    assert meta["adocument_sync_version"] == 2662
    assert meta["distinct_element_ids"] > 1000        # the donor's dangling universe
    assert tree["m_pPartitionTable"] is None           # no worksets in a family


@needs_stack
def test_inventory_of_our_document(s0e_doc):
    inv = FA.derive_family_inventory(s0e_doc)
    assert inv.self_family_id == s0e_doc.self_family.elem_id
    assert inv.self_family_id in inv.ids
    assert inv.levels and inv.refplanes            # the datum layer
    assert inv.project_view in inv.all_views
    assert inv.units_elem in inv.ids
    # geometry / connectors / params are indexed by NO registry -> not in the inventory API
    assert set(inv.levels + inv.refplanes) <= inv.ids


@needs_stack
@pytest.mark.parametrize("mode", ["candidate", "purity", "minimal"])
def test_author_family_adocument_modes(s0e_doc, mode):
    ad = FA.author_family_adocument(s0e_doc, mode=mode)
    r = ad["report"]
    g = r["gates"]
    assert g["decodes_clean"] and g["roundtrip_equal"]
    assert g["dangling_after_schema_census"] == 0
    assert g["byte_scan_donor_ids"]["hits"] == 0     # ZERO donor element ids
    assert g["donor_name_hits"] == []                # ZERO donor / employee names
    assert ad["value"]["m_ownerFamilyId"] == s0e_doc.self_family.elem_id
    live = {e.elem_id for e in s0e_doc.elements}
    # nothing referenced that is not ours (the naive collector also counts
    # small counters; the schema census above is the authority)
    assert all(i in live or i < 100 for i in g["our_ids_referenced"])
    if mode == "purity":
        assert r["forge_corpus"]["action"] == "EMPTIED"
        assert len(ad["payload"]) < 50_000
    else:
        assert r["forge_corpus"]["action"] == "CARRIED"
    if mode == "minimal":
        # only the owner names ours: no registry indexes our elements
        assert g["byte_scan_our_ids"]["distinct"] <= 1


@needs_stack
def test_candidate_indexes_exactly_our_settings_layer(s0e_doc):
    ad = FA.author_family_adocument(s0e_doc, mode="candidate")
    inv = ad["inventory"]
    tree = ad["value"]
    dbv = FA._appinfo_body(tree, "DBViewInfo")
    assert dbv["m_DBViewProjectId"] == inv.project_view
    assert dbv["m_DBViewsIndex"] == inv.all_views
    assert dbv["m_aidSunAndShadowSettings"] == inv.suns
    dat = FA._appinfo_body(tree, "DatumTracking")
    assert dat["m_elemIdSet"] == sorted(inv.levels + inv.refplanes)
    assert FA._appinfo_body(tree, "UnitsTracking")["m_unitsElemId"] == inv.units_elem
    # the built-in category catalogue: ours has none
    ctr = FA._appinfo_body(tree, "CategoryTracking")
    assert ctr["m_gstyleData"] == [] and ctr["m_categoryData"] == []
    # the settings-singleton table is all-null (K5-at-family-scale residual)
    uet = FA._appinfo_body(tree, "UniqueElementsTracking")["m_elemIds"]
    assert all(x == -1 for x in uet) and len(uet) == 93
    # no nested families: exactly the self entry
    fm = FA._appinfo_body(tree, "FamilyMgr")["m_arrLoadedFamilyInfo"]
    assert fm == [{"m_surrogateId": -1, "m_familyDocGUIDs": []}]
    # the product build constant, not the archetype's save lineage
    assert [b["m_str"] for b in tree["m_storedByRevitBuild"]] == [FA.PRODUCT_BUILD_STRING_2026]
    # sample naming memory gone
    assert FA._appinfo_body(tree, "NewItemNumber")["m_items"] == []
    assert "Elevation 0" not in " ".join(_all_strings(tree))


@needs_stack
def test_no_donor_strings_survive(s0e_doc):
    ad = FA.author_family_adocument(s0e_doc, mode="candidate")
    joined = "\x00".join(_all_strings(ad["value"])).lower()
    for token in ("racbasicsample", "hansonje", "elevation 0", "elevation 1",
                  "level 1", "a100", "revit default db server", "c:\\users\\",
                  "3d views", "ceiling plans"):
        assert token not in joined, token


@needs_stack
def test_embedded_variant_selfcheck(s0e_doc):
    emb = FA.author_family_adocument_embedded(s0e_doc)
    sc = emb["self_check"]
    assert sc["decodes_clean"] is True and sc["roundtrip_equal"] is True
    assert emb["value"]["m_storedByRevitBuild"] == []          # embedded convention
    assert emb["value"]["m_elemTable"] is not None             # inline ElemTable
    assert emb["value"]["m_pHistory"] is not None              # inline History


# ---------------------------------------------------------------------------
# 3. the clean emission + provenance
# ---------------------------------------------------------------------------

@needs_stack
def test_emit_v2_reads_back_clean(tmp_path, s0e_doc):
    out = str(tmp_path / "s0e_v2.rfa")
    rep = FA.emit_family_rfa_v2(s0e_doc, out, write_reports=False)
    v = rep["verify"]
    assert v["ok"] is True
    assert v["gzip_crc_failures"] == 0 and v["ecc_mismatch"] == 0
    assert not v["walker_errors"] and v["id_sets_identical_across_seqs"]
    # ours: the footer blob + the decoded end record
    assert rep["footer_blob_len"] == 64
    assert rep["end_record_hex"] == FA.FAMILY_END_RECORD.hex()
    # identity through rvt.identity
    assert rep["identity"]["author"] == FA.PRODUCT_NAME
    assert rep["identity"]["unique_document_guid"] == rep["identity"]["central_episode_guid"]
    # the ONE carried stream is the certified schema constant
    assert [c["stream"] for c in rep["carried"]] == ["Formats/Latest"]
    assert rep["carried"][0]["is_corpus_schema_constant"] is True


@needs_stack
def test_emit_v2_validates_and_is_provenance_clean(tmp_path, s0e_doc):
    out = str(tmp_path / "s0e_v2.rfa")
    FA.emit_family_rfa_v2(s0e_doc, out, write_reports=False)
    val = FA.validate_family_file(out, with_donor_parity=False)
    assert val["ok"] is True
    assert val["family_mode"]["verdict"] == "VALID"
    assert val["family_mode"]["n_errors"] == 0
    prov = FA.provenance_scan_v2(out)
    assert prov["ok"] is True, {k: v for k, v in prov["checks"].items() if not v}
    a = prov["adocument"]
    assert a["decodes_clean"] and a["byte_scan_donor_ids"]["hits"] == 0
    assert a["dangling_id_refs_gt99"] == 0 and a["donor_name_string_hits"] == []
    pf = prov["partition_footer"]
    assert pf["signature_string_occurrences"] == 1
    assert pf["end_record_is_decoded_constant"] is True
    assert pf["donor_footer_blob_present"] is False
    assert pf["donor_end_parity_present"] is False
    idn = prov["identity"]
    assert idn["no_employee_usernames"] and idn["no_windows_user_path"]
    assert idn["author"] == FA.PRODUCT_NAME


@needs_stack
def test_empty_footer_form(tmp_path, s0e_doc):
    out = str(tmp_path / "s0e_v2_empty.rfa")
    rep = FA.emit_family_rfa_v2(s0e_doc, out, footer_mode="empty", write_reports=False)
    assert rep["footer_blob_len"] == 0
    assert rep["verify"]["ok"] is True
    prov = FA.provenance_scan_v2(out)
    assert prov["partition_footer"]["our_footer_blob_len"] == [0]
    assert prov["checks"]["signature_string_present"] is True


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _all_strings(v, out=None):
    if out is None:
        out = []
    if isinstance(v, dict):
        for x in v.values():
            _all_strings(x, out)
    elif isinstance(v, list):
        for x in v:
            _all_strings(x, out)
    elif isinstance(v, str) and v:
        out.append(v)
    return out
