#!/usr/bin/env python
"""probe_batch.py -- THE STANDING-CONTROLS GATE + CAMPAIGN LEDGER HYGIENE
(genesis-discipline stream, 2026-08-04).

WHY THIS EXISTS.  On 2026-08-04 the campaign lost five hours because
(a) a base -- K1.rvt, 'R5 minus the placed model' -- was ASSUMED sound
instead of certified, and (b) four consecutive viewer rounds carried ZERO
known-PASS controls, so a broken base masqueraded as forty findings (see
docs/inbox/genesis-audit.md, ORCHESTRATOR VERDICTS #15 -- RETRACTION).
This tool makes both mechanically impossible for every future batch.

THE LAW IT ENFORCES (docs/inbox/genesis-audit.md 'NEW HARD LAW'):
  * a probe's declared BASE must ITSELF be listed in
    docs/coverage/viewer-certified.json 'certified' -- 'derived from a
    certified file' does NOT count; the certification claim written inside a
    probes.json ("(viewer PASS)") is prose and is IGNORED -- only the LEDGER
    counts;
  * every batch carries >= 1 certified CONTROL -- a byte-identical copy of a
    certified file, renamed CTRL_<stem>_b<n>.rvt so the viewer neither
    dedupes it nor recognises it -- generated here from the newest certified
    entry on disk;
  * the batch is staged into experiments/acceptance/ with a manifest
    batch_<n>.json recording {file, md5, base, base_certification, kind}
    for every entry, ordered CONTROL FIRST (read the oracle before anything);
  * read_batch_verdicts() interprets a round in the ONLY safe order:
    control failed  => ORACLE/ENVIRONMENT problem, every verdict VOID;
    control missing => INCOMPLETE, interpret nothing;
    a probe's base uncertified => refuse THAT probe, demand the base first;
    only then attribute a probe's FAIL to the probe's own change.

KINDS OF ENTRY.  'probe' (must declare a certified base), 'candidate-base'
(a file uploaded to BE certified so future probes may build on it -- it
needs no certified base but is only ever read as 'certify me / fail me'),
'control' (the generated byte-identical certified copy).  A probe declares
its base in ITS OWN probes.json (any of the corpus formats -- see
BASE_KEYS) or is described by the front door's own manifest.json (its
'base' block + 'build.files'); a probe with no resolvable declaration is
refused: undeclared lineage is exactly how K1 slipped through.

THE SHA256 ALIAS RULE (part of the law, 2026-08-09, #131).  The ledger keys
on repo paths under experiments/, which are git-ignored: on a fresh clone /
cloud session the certified composed bases exist only as the sha256-pinned
copies under plugin/assets/genesis/.  Certification is a fact about BYTES,
so a file whose sha256 EQUALS a certified entry's recorded 'sha256', or
equals a genesis pin (rvt.frontdoor.base GenesisPin release slot) whose
pinned relpath is itself ledger-certified, IS that certified file and reads
('certified', entry aliased to the certified path).  Exact digest equality
only -- a byte-different file that merely carries a certified BASENAME stays
'unknown', and a path the ledger records as FAILED stays failed whatever its
bytes.  The same rule lets the gate cut the batch CONTROL from the pinned
bundled base of the batch's release when no certified experiments/ file is
on disk: the copy is still byte-identical to a certified file, so the
control law is unchanged.

USAGE (repo root, .venv/bin/python):
  tools/probe_batch.py check   FILE...            # dry-run gate: violations only
  tools/probe_batch.py stage   FILE... [--candidate-base F] [--control-from F]
                                                  # gate + control + copy + batch_<n>.json
                                                  # (--manifest may name a probes.json OR a
                                                  #  front-door manifest.json)
  tools/probe_batch.py resolve FILE               # print each probe's resolved base
  tools/probe_batch.py verdicts BATCH.json --verdict K3=PASS --verdict X0=FAIL
  tools/probe_batch.py verdicts BATCH.json --verdicts-json verdicts.json
  tools/probe_batch.py retro   [--json]           # replay the whole recorded history
                                                  # through the same rules (the
                                                  # verdict-integrity audit's table)
"""
from __future__ import annotations

import argparse
import datetime as _dt
import glob
import hashlib
import json
import os
import re
import shutil
import sys
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, "docs", "coverage", "viewer-certified.json")
ACCEPTANCE = os.path.join(ROOT, "experiments", "acceptance")
CONTROL_PREFIX = "CTRL_"

# Keys inside a probes.json PROBE ENTRY that may declare the base, in
# priority order.  'template' names a symbol resolved through the manifest's
# 'reference_files' map (the addpath convention); 'parent_rung' names a
# sibling entry by 'rung' (the substitution-ladder convention).
BASE_KEYS = ("base", "derived_from", "derives_from", "template",
             "passing_sibling", "parent_rung", "known_sibling")
# Manifest-level fallbacks (a single base shared by every probe of a stream).
MANIFEST_BASE_KEYS = ("base", "start_base", "known_passing_anchors")

_PATH_RE = re.compile(r"((?:experiments|samples)/[A-Za-z0-9_./+-]+?\.(?:rvt|rfa|rte))")
_ABS_RE = re.compile(r"(/[^\s'\"(),]+?\.(?:rvt|rfa|rte))\b")
_BARE_RE = re.compile(r"(?<![A-Za-z0-9_./-])([A-Za-z0-9_+-]+\.(?:rvt|rfa|rte))\b")
_VERDICT_PASS = {"PASS", "TRANSLATION SUCCESS", "SUCCESS", "OK", "LOADED", "TRANSLATED"}
_VERDICT_FAIL_TOKENS = ("FAIL", "PROCESSING FAILED", "CORRUPT", "CRASH", "-1073741831", "-1073742517")


# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------
def rel(path: str) -> str:
    """Repo-relative POSIX path (ledger / manifest paths are repo-relative);
    a path outside the repo stays absolute."""
    a = os.path.abspath(os.path.join(ROOT, path))
    try:
        r = os.path.relpath(a, ROOT)
    except ValueError:
        return a
    if r.startswith(".."):
        return a
    return r.replace(os.sep, "/")


def abspath(path: str) -> str:
    return path if os.path.isabs(path) else os.path.join(ROOT, path)


def _digest(path: str, algo: str) -> str:
    h = hashlib.new(algo)
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def md5_of(path: str) -> str:
    return _digest(path, "md5")


def sha256_of(path: str) -> str:
    return _digest(path, "sha256")


class GateRefusal(Exception):
    """Raised when the gate refuses a batch (carries the violation list)."""

    def __init__(self, violations: List[str]):
        self.violations = violations
        super().__init__("BATCH REFUSED:\n  " + "\n  ".join(violations))


# ---------------------------------------------------------------------------
# the genesis pins (rvt.frontdoor.base GenesisPin, read-only) -- where the
# certified composed bases live on a fresh clone, and under which sha256
# ---------------------------------------------------------------------------
class PinnedBase:
    """One GenesisPin release slot: the certified composed base of one Revit
    release, its pinned sha256, and every path a byte-identical copy of it
    may sit at (the experiments/ compose output, plugin/assets/genesis/, a
    plugin bundle).  The ledger decides whether ``relpath`` is certified;
    the pin only says which BYTES that path holds."""

    def __init__(self, release: int, relpath: str, sha256: str,
                 candidates: Sequence[str] = ()):
        self.release = int(release)
        self.relpath = rel(relpath)
        self.sha256 = str(sha256).lower()
        self.candidates = [abspath(c) for c in candidates] or [abspath(self.relpath)]


def genesis_pins() -> List[PinnedBase]:
    """The release slots of the shipped genesis pin (src/rvt/frontdoor/assets/
    genesis_base.json via rvt.frontdoor.base.PIN), newest release first.
    Empty when the engine is not importable from this script's root (the
    gate then behaves exactly as before: ledger paths only)."""
    for p in (os.path.join(ROOT, "src"), os.path.join(ROOT, "lib", "src")):   # repo / plugin layout
        if os.path.isdir(p) and p not in sys.path:
            sys.path.insert(0, p)
    try:
        from rvt.frontdoor.base import PIN
    except Exception:                                        # engine absent: no pins, old rules
        return []
    pins: List[PinnedBase] = []
    for year in sorted(PIN.release_years(), reverse=True):
        slot = PIN.release_slot(year) or {}
        rp, sha = slot.get("relpath"), slot.get("sha256")
        if not rp or not sha:                                # a pending slot pins nothing
            continue
        pins.append(PinnedBase(year, str(rp), str(sha),
                               PIN.candidate_paths(relpath=str(rp))))
    return pins


# ---------------------------------------------------------------------------
# the ledger (docs/coverage/viewer-certified.json) -- the ONLY authority
# ---------------------------------------------------------------------------
class Ledger:
    """The orchestrator's viewer-certified ledger.

    ``certified`` and ``failed`` map repo-relative file paths to their entry.
    A file's certification is decided HERE and nowhere else: a probes.json
    saying "(viewer PASS)" about its base is prose, not evidence.

    ``pins`` are the genesis release slots (see PinnedBase): they let a file
    on ANY path read as a certified entry when its sha256 proves it IS that
    entry's bytes (the alias rule in the module docstring).
    """

    def __init__(self, certified: Dict[str, dict], failed: Dict[str, dict],
                 path: str = LEDGER, pins: Optional[Sequence[PinnedBase]] = None):
        self.certified = certified
        self.failed = failed
        self.path = path
        self.pins: List[PinnedBase] = list(genesis_pins() if pins is None else pins)
        self._sha_cache: Dict[str, str] = {}                 # abs path -> sha256 (hash each file once)
        # sha256 -> certified repo path: every certified entry that records its
        # own 'sha256', plus every genesis pin whose pinned relpath is ITSELF
        # in 'certified' (the pin supplies the digest the older ledger entries
        # lack; the ledger still supplies the certification)
        self.sha_index: Dict[str, str] = {}
        for p, e in certified.items():
            if e.get("sha256"):
                self.sha_index.setdefault(str(e["sha256"]).lower(), p)
        for pin in self.pins:
            if pin.relpath in certified:
                self.sha_index.setdefault(pin.sha256, pin.relpath)

    @classmethod
    def load(cls, path: str = LEDGER, pins: Optional[Sequence[PinnedBase]] = None) -> "Ledger":
        if not os.path.exists(path):
            return cls({}, {}, path, pins)
        with open(path) as fh:
            data = json.load(fh)
        cert = {rel(e["file"]): e for e in (data.get("certified") or []) if e.get("file")}
        fail = {rel(e["file"]): e for e in (data.get("failed") or []) if e.get("file")}
        return cls(cert, fail, path, pins)

    # -- the sha256 alias rule ------------------------------------------------
    def _sha256(self, relpath: str) -> Optional[str]:
        a = os.path.abspath(abspath(relpath))
        if not os.path.isfile(a):
            return None
        if a not in self._sha_cache:
            self._sha_cache[a] = sha256_of(a).lower()
        return self._sha_cache[a]

    def alias(self, relpath: str) -> Optional[Tuple[str, str]]:
        """(certified_path, sha256) when the file at ``relpath`` is byte-for-
        byte a certified entry (see sha_index), else None."""
        digest = self._sha256(relpath)
        hit = self.sha_index.get(digest) if digest else None
        return (hit, digest) if hit else None

    def pin_for(self, relpath: Optional[str]) -> Optional[PinnedBase]:
        """The genesis pin whose certified relpath IS ``relpath`` (so the
        gate knows a base's release without opening it)."""
        p = rel(relpath) if relpath else None
        return next((pin for pin in self.pins if pin.relpath == p), None)

    def pinned_certified_on_disk(self, release: Optional[int] = None) -> Optional[str]:
        """A pinned composed base that is on disk, hashes to its pin AND whose
        pinned relpath is ledger-certified -- the fresh-clone control source.
        ``release`` picks that release's slot; None = newest release first.
        A candidate copy that fails its pin's digest is not that base."""
        for pin in self.pins:
            if release is not None and pin.release != int(release):
                continue
            if pin.relpath not in self.certified:
                continue
            for c in pin.candidates:
                if self._sha256(c) == pin.sha256:
                    return rel(c)
        return None

    def control_source(self, release: Optional[int] = None) -> Optional[str]:
        """Where `stage` will cut the control from: the newest certified
        experiments/ file on disk (any release -- a certified control proves
        the ORACLE, not the probe), else the pinned bundled base of
        ``release`` (plugin/assets/genesis/*.rvt, sha-verified)."""
        return self.newest_certified_on_disk() or self.pinned_certified_on_disk(release)

    # Autodesk's own shipped sample files (samples/*.rvt|rfa) are the reader's
    # reference files -- the source every certified lineage (V0/V15/M/H/L1a)
    # built directly on.  They count as certified BASE sources.  The
    # discipline record recommends the orchestrator list them explicitly.
    @staticmethod
    def is_sample_source(relpath: str) -> bool:
        p = rel(relpath)
        return p.startswith("samples/") and os.path.exists(abspath(p))

    def status(self, relpath: Optional[str]) -> Tuple[str, Optional[dict]]:
        """('certified'|'sample'|'failed'|'unknown', entry-or-None).

        The ledger PATH decides first (certified / sample / failed); only a
        path the ledger has never heard of may then be certified BY BYTES:
        its sha256 equals a certified entry's (the alias rule) -> the entry,
        re-keyed to the certified path and stamped 'aliased_from' /
        'alias_sha256' so every reader sees which file stood in."""
        if not relpath:
            return "unknown", None
        p = rel(relpath)
        if p in self.certified:
            return "certified", self.certified[p]
        if self.is_sample_source(p):
            return "sample", {"file": p, "proves": "Autodesk-authored sample (the reader's own "
                                                   "reference file; source of every certified lineage)"}
        if p in self.failed:
            return "failed", self.failed[p]
        hit = self.alias(p)
        if hit:
            cert, digest = hit
            return "certified", {**self.certified[cert], "file": cert,
                                 "aliased_from": p, "alias_sha256": digest}
        return "unknown", None

    def newest_certified_on_disk(self, max_bytes: Optional[int] = None) -> Optional[str]:
        """Newest 'certified' entry whose file exists (the ledger array is
        maintained in chronological order, newest LAST)."""
        for p in reversed(list(self.certified.keys())):
            a = abspath(p)
            if os.path.isfile(a):
                if max_bytes is not None and os.path.getsize(a) > max_bytes:
                    continue
                return p
        return None


# ---------------------------------------------------------------------------
# probes.json discovery + base resolution
# ---------------------------------------------------------------------------
_NAME_INDEX: Optional[Dict[str, List[str]]] = None


def _name_index() -> Dict[str, List[str]]:
    """basename -> repo paths, over experiments/ (EXCLUDING the acceptance
    staging copies, which are uploads not sources) and samples/."""
    global _NAME_INDEX
    if _NAME_INDEX is not None:
        return _NAME_INDEX
    idx: Dict[str, List[str]] = {}
    for pat in ("experiments/**/*.rvt", "experiments/**/*.rfa", "samples/*.rvt", "samples/*.rfa"):
        for p in glob.glob(os.path.join(ROOT, pat), recursive=True):
            rp = rel(p)
            if rp.startswith("experiments/acceptance/"):
                continue
            idx.setdefault(os.path.basename(rp), []).append(rp)
    _NAME_INDEX = idx
    return idx


def _resolve_bare_name(name: str) -> Optional[str]:
    """Resolve a bare 'K1.rvt' to its unique repo path (WEAK -- manifests
    should declare full repo paths; ambiguity resolves to None)."""
    hits = _name_index().get(name) or []
    return hits[0] if len(hits) == 1 else None


def _first_path(text: Any) -> Optional[str]:
    """Extract the first .rvt/.rfa/.rte repo path from a free-text field.
    Full repo paths (experiments/..., samples/...) first; failing that a
    UNIQUE bare basename (the legacy subst_v2 form) -- ambiguous bare names
    resolve to nothing, on purpose."""
    if text is None:
        return None
    if isinstance(text, dict):
        for v in text.values():
            got = _first_path(v)
            if got:
                return got
        return None
    if isinstance(text, (list, tuple)):
        for v in text:
            got = _first_path(v)
            if got:
                return got
        return None
    if not isinstance(text, str):
        return None
    m = _PATH_RE.search(text)
    if m:
        return m.group(1)
    am = _ABS_RE.search(text)                                   # absolute paths (some real
    if am:                                                     # manifests, and test corpora)
        return am.group(1)
    for bm in _BARE_RE.finditer(text):
        got = _resolve_bare_name(bm.group(1))
        if got:
            return got
    return None


def _iter_probe_entries(manifest: dict) -> List[Tuple[str, dict]]:
    """[(entry_key, entry)] for a probes.json 'probes' block (list or dict),
    plus the latest-probes convention: a manifest.json 'viewer_queue' list.
    Both are yielded when both exist (a stream may keep build details under
    'probes' and the base declaration under 'viewer_queue')."""
    out: List[Tuple[str, dict]] = []
    for block in ("probes", "viewer_queue"):
        pr = manifest.get(block)
        if isinstance(pr, dict):
            for k, e in pr.items():
                if isinstance(e, dict):
                    out.append((str(k), e))
        elif isinstance(pr, list):
            for i, e in enumerate(pr):
                if isinstance(e, dict):
                    key = str(e.get("name") or e.get("rung") or e.get("id") or e.get("probe") or i)
                    out.append((key, e))
    return out


def is_frontdoor_manifest(manifest: dict) -> bool:
    """True for the front door's own manifest.json (rvt.frontdoor.manifest):
    it carries no 'probes' block but declares the run's base ('base') and
    outputs ('build.files' on the create routes, 'output' on the edit route)."""
    return ("frontdoor" in str(manifest.get("tool") or "")
            and isinstance(manifest.get("base"), dict))


def frontdoor_entries(manifest: dict, pins: Sequence[PinnedBase] = ()) -> List[Tuple[str, dict]]:
    """One probe entry per .rvt/.rfa a front-door manifest.json says it wrote
    ('build.files' / 'output'), each declaring the run's base as an exact path
    under 'base' -- the same field a probes.json uses, so resolution and the
    best-match ordering are shared:

      * manifest.base.sha256 equals a genesis pin's sha256 -> that pin's
        certified relpath (experiments/genesis/.../G_ABPD*.rvt) -- the base
        block of a --target-version 2025 run still embeds the DEFAULT pin, so
        the digest is matched against every release slot, not base.pin only;
      * else base.pin when base.sha256 == base.pin.sha256;
      * else the base file itself (an explicit --base / $RVT_GENESIS_BASE /
        the --rvt route's input): the ledger then judges that path -- by
        path or by bytes -- like any other declared base.
    'release' is the matched pin's, else target_version.output_release;
    'digest_matched' records that the declaration came from sha256 equality.
    Nothing here certifies anything; it only turns the front door's recorded
    lineage into the declaration the gate demands."""
    if not is_frontdoor_manifest(manifest):
        return []
    base = manifest.get("base") or {}
    digest = str(base.get("sha256") or "").lower()
    tv = manifest.get("target_version") if isinstance(manifest.get("target_version"), dict) else {}
    release: Optional[int] = int(tv["output_release"]) if str(tv.get("output_release") or "").isdigit() else None
    pin = next((p for p in pins if digest and digest == p.sha256), None)
    own = base.get("pin") if isinstance(base.get("pin"), dict) else {}
    if pin:
        declared, release = pin.relpath, pin.release
        how = f"base.sha256 {digest[:12]}... == the Revit {pin.release} genesis pin"
    elif digest and own.get("relpath") and digest == str(own.get("sha256") or "").lower():
        declared, how = rel(str(own["relpath"])), f"base.sha256 {digest[:12]}... == base.pin"
    elif base.get("path") or base.get("input_file"):
        declared = rel(str(base.get("path") or base.get("input_file")))
        how = f"base file {declared} (source {base.get('source') or 'input'}; not a genesis pin)"
    else:
        return []
    files = [f for f in list(((manifest.get("build") or {}).get("files") or {}).values())
             + [manifest.get("output")] if isinstance(f, dict)]
    out: List[Tuple[str, dict]] = []
    for f in files:
        p = str(f.get("path") or f.get("relpath") or "")
        if os.path.splitext(p)[1].lower() not in (".rvt", ".rfa", ".rte"):
            continue
        out.append((os.path.splitext(os.path.basename(p))[0],
                    {"file": p, "base": declared, "release": release,
                     "digest_matched": how.startswith("base.sha256"),
                     "declared_by": f"front-door manifest: {how}"}))
    return out


def candidate_manifests(probe_path: str) -> List[str]:
    """Where to look for the probe's declaration: its own directory first
    (probes.json, then manifest.json), then every manifest under
    experiments/."""
    found: List[str] = []
    d = os.path.dirname(abspath(probe_path))
    for name in ("probes.json", "manifest.json"):
        own = os.path.join(d, name)
        if os.path.exists(own):
            found.append(own)
    for pat in ("experiments/**/probes.json", "experiments/**/probes_*.json",
                "experiments/**/manifest.json"):
        for m in sorted(glob.glob(os.path.join(ROOT, pat), recursive=True)):
            if m not in found:
                found.append(m)
    return found


def find_entries(probe_path: str, manifest_override: Optional[str] = None,
                 pins: Optional[Sequence[PinnedBase]] = None
                 ) -> List[Tuple[str, dict, str, dict]]:
    """Every (manifest_path, manifest_dict, entry_key, entry) describing
    ``probe_path``, best matches first: exact repo-path match in the probe's
    own directory manifests, then exact matches elsewhere, then (WEAK) a
    basename-only match -- so a probe staged into experiments/acceptance/ still
    finds its source stream's declaration.  ``pins`` (default: the shipped
    genesis pins) let a front-door manifest.json name its pinned base.
    """
    target = rel(probe_path)
    base_name = os.path.basename(target)
    pins = genesis_pins() if pins is None else pins
    manifests = [abspath(manifest_override)] if manifest_override else candidate_manifests(probe_path)
    exact: List[Tuple[str, dict, str, dict]] = []
    weak: List[Tuple[str, dict, str, dict]] = []
    for mp in manifests:
        try:
            with open(mp) as fh:
                man = json.load(fh)
        except (OSError, ValueError):
            continue
        if not isinstance(man, dict):
            continue
        for key, e in _iter_probe_entries(man) + frontdoor_entries(man, pins):
            f = e.get("file")
            if not f:
                if key == os.path.splitext(base_name)[0]:      # symbol-named entry, no file
                    weak.append((mp, man, key, e))
                continue
            if rel(str(f)) == target:
                exact.append((mp, man, key, e))
            elif os.path.basename(str(f)) == base_name:
                weak.append((mp, man, key, e))
    return exact + weak


class BaseResolution:
    """The declared base of one probe, and where the declaration came from."""

    def __init__(self, probe: str, base: Optional[str], source: str,
                 manifest: Optional[str], raw: Optional[str] = None, *,
                 release: Optional[int] = None, digest_matched: bool = False):
        self.probe = rel(probe)
        self.base = rel(base) if base else None
        self.source = source            # human-readable: which manifest/field
        self.manifest = rel(manifest) if manifest else None
        self.raw = raw                  # the raw declaration text
        self.release = release          # the Revit release the declaring manifest names, if any
        self.digest_matched = digest_matched   # declared by sha256 == a genesis pin, not by prose

    def to_json(self) -> dict:
        return {"probe": self.probe, "base": self.base, "declared_in": self.manifest,
                "declared_by": self.source, "declaration": self.raw,
                "release": self.release, "digest_matched": self.digest_matched}


def resolve_base(probe_path: str, manifest_override: Optional[str] = None,
                 pins: Optional[Sequence[PinnedBase]] = None) -> BaseResolution:
    """Resolve the probe's DECLARED base file from its probes.json entry (or
    the front-door manifest.json that describes it).

    Resolution order (first hit wins), per describing entry (best match
    first, see find_entries):
      1. entry keys in BASE_KEYS order.  A value that names an EXISTING file
         (repo-relative or absolute) is that file, verbatim; a symbolic value
         found in the manifest's top-level 'bases' map -> that base's path;
         'template' -> manifest 'reference_files'[template]; 'parent_rung' ->
         the sibling entry whose rung/name matches (its 'file'); other keys ->
         the first repo path (experiments/... or samples/...) inside the
         value, else a UNIQUE bare filename.
      2. manifest-level MANIFEST_BASE_KEYS (a stream-wide base).
    A probe with no resolvable declaration returns base=None -- the gate
    treats that as a violation (undeclared lineage is not lineage).
    """
    hits = find_entries(probe_path, manifest_override, pins)
    if not hits:
        return BaseResolution(probe_path, None,
                              "no probes.json / front-door manifest.json entry describes this file",
                              None, None)
    last_reason: Optional[BaseResolution] = None
    for mp, man, key, entry in hits:
        got = _resolve_entry(probe_path, mp, man, key, entry)
        if got.base:
            return got
        last_reason = got
    assert last_reason is not None
    return last_reason


def _resolve_entry(probe_path: str, mp: str, man: dict, key: str, entry: dict) -> BaseResolution:
    """Resolve the base from ONE describing entry (see resolve_base)."""
    entries = _iter_probe_entries(man)
    ref_files = man.get("reference_files") if isinstance(man.get("reference_files"), dict) else {}
    bases_map = man.get("bases") if isinstance(man.get("bases"), dict) else {}
    via = f" ({entry['declared_by']})" if entry.get("declared_by") else ""
    meta = {"release": entry.get("release") if isinstance(entry.get("release"), int) else None,
            "digest_matched": bool(entry.get("digest_matched"))}
    for k in BASE_KEYS:
        if k not in entry or entry.get(k) in (None, "", [], {}):
            continue
        val = entry[k]
        raw = json.dumps(val) if not isinstance(val, str) else val
        if isinstance(val, str) and os.path.isfile(abspath(val)):      # an exact, existing path:
            return BaseResolution(probe_path, val,                        # no free-text parsing
                                  f"{rel(mp)} entry {key!r} field {k!r}{via}", mp, raw, **meta)
        # symbolic base (latest-probes convention: "base": "rst" resolved via
        # the manifest's top-level "bases": {"rst": {"path": ...}})
        if isinstance(val, str) and val in bases_map and not _first_path(val):
            got = _first_path(bases_map[val])
            if got:
                return BaseResolution(probe_path, got,
                                      f"{rel(mp)} entry {key!r} field {k!r}={val!r} "
                                      f"(-> manifest 'bases')", mp, raw)
            continue
        if k == "template" and isinstance(val, str):
            # symbolic name resolved through reference_files, else another entry
            ref = ref_files.get(val)
            got = _first_path(ref) if ref is not None else None
            if not got:
                for ek, ee in entries:
                    if ek == val or str(ee.get("rung")) == val or str(ee.get("name")) == val:
                        got = _first_path(ee.get("file"))
                        break
            if got:
                return BaseResolution(probe_path, got,
                                      f"{rel(mp)} entry {key!r} field 'template'={val!r}", mp, raw)
            continue
        if k == "parent_rung" and isinstance(val, str):
            sym = val.split()[0]
            got = None
            for ek, ee in entries:
                if str(ee.get("rung")) == sym or str(ee.get("name")) == sym or ek == sym:
                    got = _first_path(ee.get("file"))
                    break
            if not got:
                got = _first_path(val)          # e.g. "R9 (viewer PASS)" -> anchors map
                if not got:
                    anchors = man.get("known_passing_anchors") or {}
                    if isinstance(anchors, dict) and sym in anchors:
                        got = _first_path(anchors[sym])
            if got:
                return BaseResolution(probe_path, got,
                                      f"{rel(mp)} entry {key!r} field 'parent_rung'={val!r}", mp, raw)
            continue
        got = _first_path(val)
        if got:
            return BaseResolution(probe_path, got,
                                  f"{rel(mp)} entry {key!r} field {k!r}{via}", mp, raw, **meta)
    for k in MANIFEST_BASE_KEYS:
        if k not in man or man.get(k) in (None, "", [], {}):
            continue
        got = _first_path(man[k])
        if got:
            raw = json.dumps(man[k]) if not isinstance(man[k], str) else man[k]
            return BaseResolution(probe_path, got,
                                  f"{rel(mp)} manifest-level field {k!r} (stream-wide base)",
                                  mp, raw)
    return BaseResolution(probe_path, None,
                          f"{rel(mp)} entry {key!r} declares no base "
                          f"(none of {list(BASE_KEYS)} nor manifest-level "
                          f"{list(MANIFEST_BASE_KEYS)} carries a file path)", mp, None)


# ---------------------------------------------------------------------------
# the gate
# ---------------------------------------------------------------------------
class Entry:
    """One file admitted to a batch."""

    def __init__(self, file: str, kind: str, base: Optional[BaseResolution] = None):
        self.file = rel(file)
        self.kind = kind                     # 'control' | 'candidate-base' | 'probe'
        self.base = base
        self.base_status: str = "n/a"
        self.base_entry: Optional[dict] = None
        self.control_source: Optional[str] = None
        self.staged_as: Optional[str] = None
        self.md5: Optional[str] = None
        self.order: int = 0
        self.advisory: Optional[str] = None

    def to_json(self) -> dict:
        d: Dict[str, Any] = {
            "order": self.order,
            "file": self.file,
            "staged_as": self.staged_as,
            "md5": self.md5,
            "kind": self.kind,
            "control": self.kind == "control",
        }
        if self.kind == "control":
            d["control_source"] = self.control_source
            d["base"] = self.control_source
            d["base_certification"] = (self.base_entry or {}).get("proves")
            if (self.base_entry or {}).get("aliased_from"):        # cut from a pinned copy: name
                d["control_certified_as"] = self.base_entry.get("file")   # the ledger entry it IS
                d["control_sha256"] = self.base_entry.get("alias_sha256")
        else:
            d["base"] = self.base.base if self.base else None
            d["base_declared_by"] = self.base.source if self.base else None
            d["base_status"] = self.base_status
            d["base_certification"] = (self.base_entry or {}).get("proves") if self.base_entry else None
            if (self.base_entry or {}).get("aliased_from"):
                d["base_certified_as"] = self.base_entry.get("file")
        if self.advisory:
            d["advisory"] = self.advisory
        return d


def gate_probe(probe: str, ledger: Ledger, kind: str = "probe",
               manifest_override: Optional[str] = None) -> Tuple[Entry, List[str]]:
    """Resolve one probe's base and return (Entry, violations)."""
    e = Entry(probe, kind)
    v: List[str] = []
    a = abspath(e.file)
    if not os.path.isfile(a):
        v.append(f"{e.file}: file does not exist")
        return e, v
    e.md5 = md5_of(a)
    if kind == "candidate-base":
        # A file uploaded FOR certification: no certified base required, but
        # record whatever lineage its manifest declares (informational) and
        # WARN (not refuse) when that lineage is itself a recorded failure --
        # the candidate very likely inherits the defect (K2 <- K1).
        e.base = resolve_base(e.file, manifest_override, ledger.pins)
        st, entry = ledger.status(e.base.base) if e.base.base else ("undeclared", None)
        e.base_status = f"{st} (lineage informational only for a candidate-base)"
        e.base_entry = entry
        if st == "failed":
            e.advisory = (f"declared lineage {e.base.base} is a RECORDED FAILURE -- this candidate "
                          f"almost certainly inherits its defect; prefer rebuilding it on a "
                          f"certified base")
        return e, v
    e.base = resolve_base(e.file, manifest_override, ledger.pins)
    if not e.base.base:
        v.append(f"PROBE {e.file}: NO DECLARED BASE -- {e.base.source}. Every probe must "
                 f"declare its base in a probes.json (fields {list(BASE_KEYS)}) or sit next to "
                 f"the front-door manifest.json that built it; undeclared "
                 f"lineage is refused (that is how the K1 base slipped through).")
        e.base_status = "undeclared"
        return e, v
    st, entry = ledger.status(e.base.base)
    e.base_status = st
    e.base_entry = entry
    if st == "certified":
        pass
    elif st == "sample":
        pass
    elif st == "failed":
        v.append(f"PROBE {e.file}: declared BASE {e.base.base} (from {e.base.source}) is a "
                 f"RECORDED VIEWER FAILURE in the ledger ({(entry or {}).get('verdict', 'FAILED')}"
                 f", {(entry or {}).get('when', 'time n/a')}). A probe on a FAILED base tests "
                 f"nothing: rebase it on a certified file, or upload the fixed base as a "
                 f"candidate-base first.")
    else:
        v.append(f"PROBE {e.file}: declared BASE {e.base.base} (from {e.base.source}) is NOT "
                 f"in docs/coverage/viewer-certified.json 'certified'. 'Derived from a certified "
                 f"file' does not count and the manifest's own '(viewer PASS)' prose is not "
                 f"evidence -- the base must ITSELF be viewer-certified before anything is built "
                 f"on it. Upload {e.base.base} as a candidate-base first (with a control), certify "
                 f"it, then re-propose this probe.")
    return e, v


def check_batch(probes: Sequence[str], ledger: Optional[Ledger] = None, *,
                candidate_bases: Sequence[str] = (),
                manifest_override: Optional[str] = None) -> Tuple[List[Entry], List[str]]:
    """Gate a proposed batch WITHOUT staging.  Returns (entries, violations).
    An empty violation list means the batch is admissible (a control is added
    at stage time)."""
    ledger = ledger or Ledger.load()
    entries: List[Entry] = []
    violations: List[str] = []
    seen: Dict[str, str] = {}
    for kind, files in (("candidate-base", candidate_bases), ("probe", probes)):
        for f in files:
            e, v = gate_probe(f, ledger, kind=kind, manifest_override=manifest_override)
            entries.append(e)
            violations.extend(v)
            bn = os.path.basename(e.file)
            if bn in seen and seen[bn] != e.file:
                violations.append(f"{e.file}: BASENAME COLLISION with {seen[bn]} -- the viewer "
                                  f"and the acceptance folder key on the file NAME; rename one.")
            seen[bn] = e.file
    if not probes and not candidate_bases:
        violations.append("empty batch: nothing to gate")
    return entries, violations


def batch_release(entries: Sequence[Entry], ledger: Ledger) -> Optional[int]:
    """The ONE Revit release the batch's probes declare (so a fresh-clone
    control is cut from the same release's composed base): the release the
    declaring manifest names, else the genesis pin the declared base IS.
    None when nothing names a release or the probes disagree."""
    years = set()
    for e in entries:
        if not (e.base and e.base.base):
            continue
        pin = ledger.pin_for(e.base.base)
        year = e.base.release or (pin.release if pin else None)
        if year:
            years.add(int(year))
    return years.pop() if len(years) == 1 else None


# ---------------------------------------------------------------------------
# control generation + staging
# ---------------------------------------------------------------------------
#: The genesis campaign consumed viewer rounds 1..14 before this gate existed
#: (docs/writer/verdict-integrity-audit.md); gated batches continue from 15
#: so a manifest number never collides with a historical round number.
HISTORICAL_ROUNDS = 14


#: Environment floor for batch numbers (#285): coord's `/batches k` reservation replies with a
#: range nobody else can be given; exporting its first number here makes EVERY stager that goes
#: through next_batch_number() honour it (most tools compute their own number and never see a
#: --batch flag). "highest local + 1" alone collides whenever two sessions branch from one main.
BATCH_FLOOR_ENV = "RVT_BATCH_FLOOR"


def next_batch_number(out_dir: str = ACCEPTANCE) -> int:
    n = HISTORICAL_ROUNDS
    for p in glob.glob(os.path.join(out_dir, "batch_*.json")):
        m = re.match(r"batch_(\d+)\.json$", os.path.basename(p))
        if m:
            n = max(n, int(m.group(1)))
    floor = os.environ.get(BATCH_FLOOR_ENV, "").strip()
    return max(n + 1, int(floor)) if floor.isdigit() else n + 1


def make_control(ledger: Ledger, batch_n: int, out_dir: str = ACCEPTANCE, *,
                 source: Optional[str] = None, release: Optional[int] = None) -> Entry:
    """Generate the batch's certified CONTROL: a byte-identical copy of a
    certified file, renamed CTRL_<stem>_b<n><ext> (the CTRL_ prefix + batch
    tag defeat the viewer's name/content dedupe; the BYTES are untouched, so
    the source's certification carries over exactly).

    Source: ``source`` if given, else the newest certified experiments/ file
    on disk, else (fresh clone) the pinned bundled composed base of
    ``release`` under plugin/assets/genesis/ -- admitted only because its
    sha256 proves it IS a ledger-certified file (Ledger.status alias rule)."""
    src = rel(source) if source else ledger.control_source(release)
    if not src:
        raise GateRefusal(["cannot generate a control: no certified file exists on disk "
                           "(ledger empty or every certified file missing, and no pinned "
                           "genesis base under plugin/assets/genesis/ hashes to a certified pin)"])
    st, entry = ledger.status(src)
    if st not in ("certified", "sample"):
        raise GateRefusal([f"control source {src} is not certified (status {st}) -- a control "
                           f"must be a byte-identical copy of a CERTIFIED file"])
    a = abspath(src)
    if not os.path.isfile(a):
        raise GateRefusal([f"control source {src} does not exist on disk"])
    stem, ext = os.path.splitext(os.path.basename(src))
    if stem.startswith(CONTROL_PREFIX):
        stem = stem[len(CONTROL_PREFIX):]
        stem = re.sub(r"_b\d+$", "", stem)
    name = f"{CONTROL_PREFIX}{stem}_b{batch_n}{ext or '.rvt'}"
    os.makedirs(out_dir, exist_ok=True)
    dst = os.path.join(out_dir, name)
    shutil.copyfile(a, dst)
    src_md5 = md5_of(a)
    dst_md5 = md5_of(dst)
    if src_md5 != dst_md5:                                   # paranoia: the copy IS the point
        raise GateRefusal([f"control copy is not byte-identical to {src} ({dst_md5} != {src_md5})"])
    e = Entry(dst, "control")
    e.staged_as = rel(dst)
    e.md5 = dst_md5
    e.control_source = rel(src)
    e.base_status = st
    e.base_entry = entry
    return e


def stage_batch(probes: Sequence[str], *, candidate_bases: Sequence[str] = (),
                control_from: Optional[str] = None, out_dir: str = ACCEPTANCE,
                batch_n: Optional[int] = None, manifest_override: Optional[str] = None,
                copy: bool = True, ledger: Optional[Ledger] = None,
                note: str = "") -> dict:
    """Gate + control + stage + manifest.  Raises GateRefusal on violation.

    Writes <out_dir>/batch_<n>.json and copies every probe into out_dir
    (unless copy=False), returning the manifest dict.
    """
    ledger = ledger or Ledger.load()
    entries, violations = check_batch(probes, ledger, candidate_bases=candidate_bases,
                                      manifest_override=manifest_override)
    if violations:
        raise GateRefusal(violations)
    n = batch_n
    if not n:
        n = next_batch_number(out_dir)
        floor = os.environ.get(BATCH_FLOOR_ENV, "").strip()
        if floor and not floor.isdigit():
            print(f"warning: {BATCH_FLOOR_ENV}={floor!r} is not a number — ignored", file=sys.stderr)
        if not floor.isdigit():
            # "highest local + 1" is only right when nobody else is staging: two sessions branching
            # from the same main both took 57..59 (PRs #277/#283). coord's `/batches k` reply (#285)
            # is the collision-free source — pass it as --batch, or export it as RVT_BATCH_FLOOR.
            print(f"note: batch number {n} chosen locally (highest staged + 1). If other sessions may be "
                  f"staging too, reserve first — comment `/batches <k>` on your issue — and pass the "
                  f"number coord replies with as --batch (or export {BATCH_FLOOR_ENV}=<N>).", file=sys.stderr)
    control = make_control(ledger, n, out_dir, source=control_from,
                           release=batch_release(entries, ledger))
    os.makedirs(out_dir, exist_ok=True)
    ordered: List[Entry] = [control] + [e for e in entries if e.kind == "candidate-base"] + \
                           [e for e in entries if e.kind == "probe"]
    for i, e in enumerate(ordered):
        e.order = i
        if e.kind == "control":
            continue
        src = abspath(e.file)
        dst = os.path.join(out_dir, os.path.basename(e.file))
        if copy:
            if os.path.abspath(src) != os.path.abspath(dst):
                if os.path.exists(dst) and md5_of(dst) != e.md5:
                    raise GateRefusal([f"{e.file}: a DIFFERENT file already sits at {rel(dst)} "
                                       f"(md5 {md5_of(dst)} vs {e.md5}); rename the probe -- "
                                       f"never overwrite a staged file the viewer may already "
                                       f"have read"])
                shutil.copyfile(src, dst)
            e.staged_as = rel(dst)
        else:
            e.staged_as = rel(src)
    manifest = {
        "batch": n,
        "created": _dt.datetime.now().astimezone().isoformat(timespec="seconds"),
        "tool": "tools/probe_batch.py",
        "law": ("every entry's declared base is ITSELF in viewer-certified.json 'certified' "
                "(or is an Autodesk sample source); the batch carries >= 1 CONTROL = a "
                "byte-identical copy of a certified file; read the round with "
                "read_batch_verdicts(): control FAIL => every verdict VOID"),
        "ledger": rel(ledger.path),
        "control_count": 1,
        "note": note,
        "reading_order": [os.path.basename(e.staged_as or e.file) for e in ordered],
        "entries": [e.to_json() for e in ordered],
    }
    path = os.path.join(out_dir, f"batch_{n}.json")
    with open(path, "w") as fh:
        json.dump(manifest, fh, indent=1)
    manifest["manifest_path"] = rel(path)
    return manifest


# ---------------------------------------------------------------------------
# verdict interpretation -- the ONLY safe reading order
# ---------------------------------------------------------------------------
def normalise_verdict(v: Any) -> str:
    """Map a raw viewer verdict to PASS / FAIL / PENDING."""
    if v is None:
        return "PENDING"
    if isinstance(v, bool):
        return "PASS" if v else "FAIL"
    s = str(v).strip().upper()
    if not s or s in ("PENDING", "QUEUED", "UNKNOWN", "?", "NONE", "NULL"):
        return "PENDING"
    if s in _VERDICT_PASS or s.startswith("PASS"):
        return "PASS"
    if any(tok in s for tok in _VERDICT_FAIL_TOKENS):
        return "FAIL"
    return "PENDING"


def _match_verdict(entry: dict, verdicts: Dict[str, Any]) -> Any:
    """Find the verdict for a manifest entry: by staged path, source path,
    basename, or stem."""
    keys = []
    for k in (entry.get("staged_as"), entry.get("file")):
        if k:
            keys += [k, os.path.basename(k), os.path.splitext(os.path.basename(k))[0]]
    for k in keys:
        if k in verdicts:
            return verdicts[k]
    return None


def read_batch_verdicts(manifest: dict, verdicts: Dict[str, Any],
                        ledger: Optional[Ledger] = None) -> dict:
    """INTERPRET a round.  The order below is the whole point:

      1. CONTROL first.  Any control FAIL => the ORACLE / ENVIRONMENT is
         suspect (or the upload deduped/staled): every other verdict in the
         round is VOID -- nothing is attributed, nothing enters the ledger.
         Control PENDING/missing => the round is INCOMPLETE: interpret nothing
         until the control reads.  (A round with zero controls is refused
         outright -- it was never a legal batch.)
      2. Each probe's base is RE-CHECKED against the current ledger.  A base
         that has never been certified => refuse to interpret THAT probe and
         demand the base be uploaded (as a candidate-base) first: on an
         uncertified base a FAIL cannot be attributed to the probe's change.
      3. Only then: a probe FAIL is attributed to the probe's ONE change vs
         its certified base; a probe/candidate-base PASS is a certification.
    Returns a structured interpretation incl. suggested ledger updates.
    """
    ledger = ledger or Ledger.load()
    entries = list(manifest.get("entries") or [])
    controls = [e for e in entries if e.get("control") or e.get("kind") == "control"]
    others = [e for e in entries if not (e.get("control") or e.get("kind") == "control")]
    out: Dict[str, Any] = {
        "batch": manifest.get("batch"),
        "manifest": manifest.get("manifest_path"),
        "status": None,
        "message": "",
        "control_results": [],
        "per_file": [],
        "ledger_updates": {"certified": [], "failed": []},
        "actions": [],
    }
    if not controls:
        out["status"] = "REFUSED_NO_CONTROL"
        out["message"] = ("the round carried NO certified control: it can prove nothing about "
                          "the oracle, so no verdict in it is interpretable. This is the four-round "
                          "failure of 2026-08-04. Re-upload with a CTRL_ copy (probe_batch.py stage).")
        out["actions"].append("re-stage the same files through the gate; it adds the control")
        for e in others:
            raw = _match_verdict(e, verdicts)
            out["per_file"].append({"file": e.get("file"), "kind": e.get("kind"),
                                    "raw_verdict": raw, "reading": "UNGUARDED -- round has no "
                                    "control; do not attribute"})
        return out
    # ---- 1. controls -------------------------------------------------------
    ctrl_pending = ctrl_fail = 0
    for c in controls:
        raw = _match_verdict(c, verdicts)
        norm = normalise_verdict(raw)
        out["control_results"].append({"file": c.get("staged_as") or c.get("file"),
                                       "source": c.get("control_source"),
                                       "raw_verdict": raw, "verdict": norm})
        if norm == "FAIL":
            ctrl_fail += 1
        elif norm == "PENDING":
            ctrl_pending += 1
    if ctrl_fail:
        out["status"] = "VOID_ROUND"
        out["message"] = ("A CERTIFIED CONTROL FAILED (a byte-identical copy of a viewer-PASSED "
                          "file did not pass). This is an ORACLE / ENVIRONMENT problem -- service "
                          "degradation, throttling, a stale/deduped read, or an upload fault -- NOT "
                          "a finding about any file. EVERY OTHER VERDICT IN THIS ROUND IS VOID. "
                          "Pause the loop; re-upload a fresh control ALONE; interpret nothing until "
                          "a control passes; then re-upload this round's files.")
        out["actions"] += ["pause probe uploads",
                           "upload a fresh certified control ALONE and wait for its PASS",
                           "re-upload every file of this round in a new batch (new manifest)",
                           "do NOT enter any of this round's verdicts into the ledger"]
        for e in others:
            out["per_file"].append({"file": e.get("file"), "kind": e.get("kind"),
                                    "raw_verdict": _match_verdict(e, verdicts),
                                    "reading": "VOID -- control failed; the round did not measure"})
        return out
    if ctrl_pending:
        out["status"] = "INCOMPLETE"
        out["message"] = ("the control has not read out yet: interpret NOTHING in this round until "
                          "the control's verdict arrives (the control is read FIRST, always)")
        out["actions"].append("wait for the control verdict; re-run read_batch_verdicts")
        for e in others:
            out["per_file"].append({"file": e.get("file"), "kind": e.get("kind"),
                                    "raw_verdict": _match_verdict(e, verdicts),
                                    "reading": "PENDING -- awaiting control"})
        return out
    # ---- 2. + 3. probes / candidate-bases ----------------------------------
    refused = attributed = pending = 0
    for e in others:
        raw = _match_verdict(e, verdicts)
        norm = normalise_verdict(raw)
        rec: Dict[str, Any] = {"file": e.get("file"), "kind": e.get("kind"),
                               "raw_verdict": raw, "verdict": norm}
        kind = e.get("kind")
        if kind == "candidate-base":
            if norm == "PASS":
                rec["reading"] = "CERTIFIED (candidate-base PASS): add to 'certified'; probes may now build on it"
                out["ledger_updates"]["certified"].append(
                    {"file": e.get("file"),
                     "proves": "viewer PASS as a candidate BASE (batch %s, control passed)" % manifest.get("batch")})
                attributed += 1
            elif norm == "FAIL":
                rec["reading"] = ("CANDIDATE BASE FAILS on its own: record in 'failed'; NOTHING may be "
                                  "built on it and anything already derived from it is VOID; bisect "
                                  "its construction (its own base is: %s)" % e.get("base"))
                out["ledger_updates"]["failed"].append(
                    {"file": e.get("file"), "verdict": "PROCESSING FAILED",
                     "note": "candidate BASE failed in batch %s with the control PASSING -- a real "
                             "defect of the file itself; every probe built on it is VOID" % manifest.get("batch")})
                attributed += 1
            else:
                rec["reading"] = "PENDING"
                pending += 1
            out["per_file"].append(rec)
            continue
        # probe: re-check the base NOW (the ledger is the authority, and it may have moved)
        base = e.get("base")
        st, _entry = ledger.status(base) if base else ("undeclared", None)
        rec["base"] = base
        rec["base_status_now"] = st
        if norm == "PENDING":
            rec["reading"] = "PENDING"
            pending += 1
            out["per_file"].append(rec)
            continue
        if st not in ("certified", "sample"):
            rec["reading"] = ("REFUSED -- the probe's own BASE %s has never been certified (status: "
                              "%s). A %s on an uncertified base is not attributable to the probe's "
                              "change. Upload %s as a candidate-base with a control, certify it, then "
                              "re-read." % (base, st, norm, base))
            out["actions"].append("upload the base %s as a candidate-base first" % base)
            refused += 1
            out["per_file"].append(rec)
            continue
        if norm == "PASS":
            rec["reading"] = ("PASS on a certified base with the control passing: the file is "
                              "certifiable; its ONE change vs %s is reader-accepted" % base)
            out["ledger_updates"]["certified"].append(
                {"file": e.get("file"),
                 "proves": "viewer PASS (batch %s; base %s certified; control passed)"
                           % (manifest.get("batch"), base)})
        else:
            rec["reading"] = ("ATTRIBUTED FAIL: base %s is certified and the control passed, so this "
                              "FAIL is REAL evidence and it convicts the probe's ONE stated change "
                              "vs that base. Read the card message; bisect that change." % base)
            out["ledger_updates"]["failed"].append(
                {"file": e.get("file"), "verdict": "PROCESSING FAILED",
                 "note": "SOUND finding (batch %s: base %s certified, control passed) -- attributable "
                         "to the probe's single change vs its base" % (manifest.get("batch"), base)})
        attributed += 1
        out["per_file"].append(rec)
    if refused and not attributed:
        out["status"] = "REFUSED_UNCERTIFIED_BASE"
        out["message"] = ("the control PASSED (oracle healthy) but the probes' own BASE(S) have never "
                          "been certified: no failure is attributable. Upload the base(s) first.")
    elif refused:
        out["status"] = "INTERPRETED_PARTIAL"
        out["message"] = ("control PASSED; %d verdict(s) attributed; %d refused (uncertified base); "
                          "%d pending" % (attributed, refused, pending))
    elif pending and not attributed:
        out["status"] = "INCOMPLETE"
        out["message"] = "control PASSED; probe verdicts pending"
    else:
        out["status"] = "INTERPRETED"
        out["message"] = ("control PASSED (oracle healthy): %d verdict(s) attributed; %d pending"
                          % (attributed, pending))
    return out


# ---------------------------------------------------------------------------
# RETRO: replay the recorded history through the same rules
# ---------------------------------------------------------------------------
# The genesis campaign's fourteen viewer rounds (2026-08-03 ~14:45 -> 2026-
# 08-04 ~02:45), transcribed from docs/inbox/genesis-audit.md (ORCHESTRATOR
# VERDICTS #1..#15) and docs/coverage/viewer-certified.json ('when' fields).
# Each upload names its immediate BASE (the file its stated change was made
# to).  'certified_before' = files viewer-certified BEFORE the campaign (the
# pre-genesis acceptance batches 1-10: V15..V32-era, H1/H2, M2..M4,
# R0_identity, R4s) -- see docs/acceptance-log.md + the ledger.  Autodesk's
# own samples (samples/*.rvt) are certified sources by definition.
HISTORY_PREGENESIS_CERTIFIED = [
    "experiments/acceptance/V15_regzip_ecc_full.rvt",
    "experiments/acceptance/V18_first_authored_change.rvt",
    "experiments/acceptance/V19_authored_change_stamped.rvt",
    "experiments/acceptance/V20_first_created_element.rvt",
    "experiments/acceptance/V21_batch_four_columns.rvt",
    "experiments/acceptance/V22_first_created_wall.rvt",
    "experiments/acceptance/V23_electrical_room.rvt",
    "experiments/acceptance/V25_room_from_ifc.rvt",
    "experiments/acceptance/V26_room_from_ifc_with_walls.rvt",
    "experiments/acceptance/V27_room_from_file_template.rvt",
    "experiments/acceptance/V28_room_clean_connectors.rvt",
    "experiments/acceptance/V29_room_with_circuits.rvt",
    "experiments/hosting/H1_panel_on_existing_wall.rvt",
    "experiments/hosting/H2_panel_on_created_wall.rvt",
    "experiments/genesis/R0_identity.rvt",
    "experiments/genesis/R4s.rvt",
    "experiments/manipulate/M2_delete_cascade.rvt",
    "experiments/manipulate/M3_modify.rvt",
    "experiments/manipulate/M4_move_retype.rvt",
    "experiments/manipulate/M2_delete_cascade_rac.rvt",
    "experiments/acceptance/V30_own_identity_keep_author.rvt",
    "experiments/acceptance/V31_own_identity_own_author.rvt",
]

K1 = "experiments/genesis/triage/K1.rvt"
RST = "samples/rstbasicsampleproject.rvt"

HISTORY_ROUNDS: List[dict] = [
    {"round": 1, "when": "08-03 ~14:45 -> verdicts #1 ~14:50",
     "uploads": [
         {"file": "experiments/genesis/G0.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G0d.rvt (assembler ladder G0a->G0d, never uploaded)",
          "recorded_cause": "lead suspect: 6,175 dangling ids in Global/Latest",
          "later": "REFUTED by R5/R9 PASS (dangling tolerated at any scale); the G0-ladder rungs "
                   "G0a..G0d were never viewer-tested, so G0's own failing step is unlocalised"},
         {"file": "experiments/acceptance/V32_own_dit_usernames.rvt", "verdict": "PASS", "base": RST},
         {"file": "experiments/genesis/types/T_conduit_types.rvt", "verdict": "PASS",
          "base": "samples/rmebasicsampleproject.rvt"},
     ]},
    {"round": 2, "when": "08-03 ~15:51 -> verdicts #2 ~16:00",
     "uploads": [
         {"file": "experiments/genesis/R5.rvt", "verdict": "PASS", "base": RST},
         {"file": "experiments/genesis/R5s.rvt", "verdict": "PASS", "base": RST},
         {"file": "experiments/genesis/R10b.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/R10.rvt (rung R10, never uploaded)",
          "recorded_cause": "embedded family-document machinery required (later: unit-removal "
                            "incoherence)",
          "later": "the removal claim was re-run on the CERTIFIED R9 as R9b (round 3, SOUND) and "
                   "refined by KD1: family documents are NOT required; COHERENT four-registry "
                   "reconciliation is. R10b itself sits on the uncertified R10 rung."},
     ]},
    {"round": 3, "when": "08-03 ~16:56 -> verdicts #3 ~17:05",
     "uploads": [
         {"file": "experiments/genesis/R9.rvt", "verdict": "PASS", "base": RST},
         {"file": "experiments/genesis/R9b.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/R9.rvt",
          "recorded_cause": "unit-removal / content-registry incoherence is the killer",
          "later": "CONFIRMED: KD1 (R9b's exact removal, four registries reconciled) PASSED in "
                   "round 5 -- Bug B named and fixed"},
     ]},
    {"round": 4, "when": "08-03 ~17:56 -> verdicts #4 ~18:15",
     "uploads": [
         {"file": "experiments/genesis/G1_candidate.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G0.rvt (viewer-FAILED, round 1)",
          "recorded_cause": "two-bug model: Bug A skeleton completeness + Bug B splice",
          "later": "Bug B was real (R9b/KD1, R9 lineage); Bug A ('settings singletons / catalog "
                   "required') rests only on K1-lineage failures and is VOID (verdict #15)"},
         {"file": "experiments/genesis/G1a.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G0.rvt (viewer-FAILED, round 1)"},
         {"file": "experiments/genesis/G1b.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G0.rvt (viewer-FAILED, round 1)"},
         {"file": "experiments/genesis/latest/probes/P4_ids_null.rvt", "verdict": "FAIL",
          "base": RST, "read_out": "verdict landed at #6 (~20:25) after K4/KD1/K3 PASSed",
          "recorded_cause": "nulling LIVE registry ids on a WORKING base is fatal; dangling ids "
                            "of deleted elements are tolerated",
          "later": "stands: on the certified rst working base; the interleaved K-passes prove the "
                   "oracle healthy across its read-out window"},
         {"file": "experiments/genesis/latest/probes/P6_all.rvt", "verdict": "FAIL", "base": RST,
          "read_out": "verdict landed at #6 (~20:25)",
          "later": "stands (dominated by P4)"},
     ]},
    {"round": 5, "when": "08-03 ~19:15-19:25 -> verdicts #6 ~20:25",
     "uploads": [
         {"file": "experiments/genesis/triage/K3.rvt", "verdict": "PASS",
          "base": "experiments/genesis/R9.rvt"},
         {"file": "experiments/genesis/triage/K4.rvt", "verdict": "PASS",
          "base": "experiments/genesis/triage/K3.rvt (co-PASSed this round)"},
         {"file": "experiments/genesis/triage/KD1.rvt", "verdict": "PASS",
          "base": "experiments/genesis/R9.rvt"},
         {"file": "experiments/genesis/triage/K5.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "THE SETTINGS SINGLETONS ARE REQUIRED (Bug A component 1)",
          "later": "VOID -- K1 (never uploaded until round 14) FAILS on its own"},
         {"file": "experiments/genesis/triage/K6.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "THE STYLE CATALOG IS REQUIRED (Bug A component 2)",
          "later": "VOID -- K1 lineage"},
     ]},
    {"round": 6, "when": "08-03 ~20:45 -> verdicts #7 ~21:05",
     "uploads": [
         {"file": "experiments/genesis/loader/L1a_rstbasic_loaded_levelhead.rvt", "verdict": "PASS",
          "base": RST},
         {"file": "experiments/genesis/singletons/S5.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G1_candidate.rvt (viewer-FAILED, round 4)",
          "recorded_cause": "our singletons/catalog on the G1 base still trip DocumentCorruption",
          "later": "VOID -- content tested on a base that had ITSELF failed (their own note "
                   "concedes the confound)"},
         {"file": "experiments/genesis/singletons/S4.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G1_candidate.rvt (viewer-FAILED, round 4)"},
         {"file": "experiments/genesis/singletons/S3.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G1_candidate.rvt (viewer-FAILED, round 4)"},
         {"file": "experiments/genesis/singletons/S1.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/G1_candidate.rvt (viewer-FAILED, round 4)"},
     ]},
    {"round": 7, "when": "08-03 ~21:10 (verdict #8, unnumbered in the audit)",
     "uploads": [
         {"file": "experiments/genesis/triage/K5a.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "singleton-subset removal from K1 fatal (subset bisection)",
          "later": "VOID -- K1 lineage"},
         {"file": "experiments/genesis/triage/K5d.rvt", "verdict": "FAIL", "base": K1,
          "later": "VOID -- K1 lineage"},
     ]},
    {"round": 8, "when": "08-03 ~22:47 -> verdicts #9 ~23:00",
     "uploads": [
         {"file": "experiments/genesis/addback/R1.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/triage/K5.rvt (viewer-FAILED, round 5; K1 lineage)",
          "recorded_cause": "every file carrying our CONSTRUCTED objects fails; the divide is "
                            "constructed vs cloned (verdict #9)",
          "later": "RETRACTED (#15): the whole K1 lineage sits on a base that fails alone"},
         {"file": "experiments/genesis/addback/R2.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/triage/K6.rvt (viewer-FAILED, round 5; K1 lineage)"},
         {"file": "experiments/genesis/addback/R3.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/singletons/S5.rvt (viewer-FAILED, round 6; G1 lineage)"},
         {"file": "experiments/genesis/subst/X5.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/subst/X4.rvt (never uploaded; cumulative K1 lineage)"},
         {"file": "experiments/genesis/subst/X9.rvt", "verdict": "FAIL",
          "base": "experiments/genesis/subst/X8.rvt (never uploaded; cumulative K1 lineage)"},
     ]},
    {"round": 9, "when": "08-03 ~23:11 -> verdicts #10 ~23:40",
     "uploads": [
         {"file": "experiments/genesis/subst/X1.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "our imperial scale keys {24..768} vs the corpus constant "
                            "{10,20,50,100,200,500} (fixer prediction)",
          "later": "VOID as a FAIL (K1 lineage) -- the corpus FACT (scale-key set) is a "
                   "descriptive law of real files and survives independently of this verdict"},
     ]},
    {"round": 10, "when": "08-04 ~00:20-00:25 -> verdicts #11 ~00:35",
     "uploads": [
         {"file": "experiments/genesis/controls/X0.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "THE DECISIVE READOUT: the ADD PATH itself corrupts (verdict #11)",
          "later": "RETRACTED (#15)"},
         {"file": "experiments/genesis/controls/X1u.rvt", "verdict": "FAIL", "base": K1},
         {"file": "experiments/genesis/controls/C0.rvt", "verdict": "FAIL", "base": K1},
         {"file": "experiments/genesis/subst_v2/X_pen.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "in-place pen-table payload rejected (the second 'independent "
                            "constraint' of #13)",
          "later": "RETRACTED (#15)"},
         {"file": "experiments/genesis/subst_v2/X_cat.rvt", "verdict": "FAIL", "base": K1},
     ]},
    {"round": 11, "when": "08-04 ~00:42 -> ~00:50",
     "uploads": [
         {"file": "experiments/genesis/controls/X0k.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "CRASH signature -1073741831 (no corruption line) -- 'a distinct "
                            "failure mode'",
          "later": "VOID (K1 lineage) -- retrospectively the FIRST sighting of K1's own death "
                   "signature (X0k = K1 + zero-motion re-add; the crash was K1's, not the re-add's)"},
     ]},
    {"round": 12, "when": "08-04 ~00:55 -> verdicts #13 ~01:55",
     "note": "THE FIRST DELIBERATE CERTIFIED CONTROLS (12 hours and 11 rounds into the campaign)",
     "uploads": [
         {"file": "experiments/acceptance/CTRL_L1a_recheck.rvt", "verdict": "PASS", "kind": "control",
          "base": "experiments/genesis/loader/L1a_rstbasic_loaded_levelhead.rvt"},
         {"file": "experiments/acceptance/CTRL_R9_recheck.rvt", "verdict": "PASS", "kind": "control",
          "base": "experiments/genesis/R9.rvt"},
     ]},
    {"round": 13, "when": "08-04 ~02:03 -> verdicts #14 ~02:25",
     "note": "XR_null was staged as the round's 'positive control' -- but it is a copy of the "
             "UNCERTIFIED K1, so it was not a control; and its read was stale (never happened)",
     "uploads": [
         {"file": "experiments/genesis/regadd/XR0.rvt", "verdict": "FAIL", "base": K1,
          "recorded_cause": "constraint 2 = commit-path re-chunking (crash signature)",
          "later": "RETRACTED (#15)"},
         {"file": "experiments/genesis/regadd/XA2.rvt", "verdict": "FAIL", "base": K1},
         {"file": "experiments/genesis/addpath/P_ep_only.rvt", "verdict": "FAIL", "base": K1},
         {"file": "experiments/genesis/addpath/P_pos_only.rvt", "verdict": "FAIL", "base": K1},
         {"file": "experiments/genesis/addpath/P_ident_only.rvt", "verdict": "FAIL", "base": K1},
     ]},
    {"round": 14, "when": "08-04 ~02:27 -> verdicts #15 ~02:45 (THE RETRACTION)",
     "note": "no control INSIDE the round: oracle health rests on round 12's certified controls "
             "(50 min earlier) plus internal consistency -- K1_base and XR_null are BYTE-IDENTICAL "
             "and BOTH crash -1073741831; a sick oracle would not track byte-identity",
     "uploads": [
         {"file": K1, "verdict": "FAIL", "kind": "candidate-base",
          "base": "experiments/genesis/R5.rvt", "uploaded_as": "K1_base.rvt",
          "recorded_cause": "K1 ITSELF is broken: the triage stream's maximal-GC 'R5 minus the "
                            "placed model' reduction introduced a CRASH defect",
          "later": "DECISIVE: the base of every X/S/R/K5x/P/XR/XA rung fails alone => verdicts "
                   "#9-#14 RETRACTED. Base R5 certified => this FAIL is attributable to K1's own "
                   "construction. Split file already staged by the triage stream: "
                   "K1_step1_neutralised.rvt"},
         {"file": "experiments/genesis/regadd/XR_null.rvt", "verdict": "FAIL", "base": K1,
          "note": "byte-identical to K1 through the pipeline; NOT in the ledger's 'failed' list "
                  "(a ledger omission)"},
     ]},
]


def _basefile(text: str) -> Optional[str]:
    """Reduce a HISTORY 'base' description to its file path."""
    return _first_path(text)


def classify_history(rounds: Sequence[dict] = HISTORY_ROUNDS) -> List[dict]:
    """Replay every recorded genesis verdict through the standing-controls
    rules and classify it:

      SOUND      base certified at (or PASS-co-uploaded in) verdict time AND the
                 round carried >= 1 known-PASS file (a passing certified copy,
                 or a co-uploaded file that PASSED -- historically the only
                 controls there were).
      UNGUARDED  base was fine but the round carried NO passing control: the
                 verdict is probably real but the round could not prove the
                 oracle healthy (retro-confirmed by the ~01:55 CTRL passes).
      VOID       the base was NEVER certified, or had ITSELF failed: the
                 verdict is an artefact candidate, not evidence.
    A PASS is self-certifying and reads SURVIVES.  This is exactly
    read_batch_verdicts() applied to history: control-then-base-then-probe.
    """
    # certification timeline: file -> round when its PASS was recorded
    certified_at: Dict[str, int] = {p: 0 for p in HISTORY_PREGENESIS_CERTIFIED}
    failed_at: Dict[str, int] = {}
    # pre-scan: when did each file eventually FAIL (to annotate 'NEVER certified' bases)
    fails_eventual: Dict[str, int] = {}
    for r in rounds:
        for u in r["uploads"]:
            if normalise_verdict(u["verdict"]) == "FAIL":
                fails_eventual.setdefault(rel(u["file"]), r["round"])
    rows: List[dict] = []
    for r in rounds:
        rn = r["round"]
        ups = r["uploads"]
        # a round is GUARDED if any upload in it PASSED (co-uploaded candidates
        # were the only 'controls' before round 12) -- passes are computed in
        # the same loop so a same-round PASS guards its neighbours.
        passers = [u["file"] for u in ups if normalise_verdict(u["verdict"]) == "PASS"]
        guarded = bool(passers)
        deliberate = [u["file"] for u in ups if u.get("kind") == "control"
                      and normalise_verdict(u["verdict"]) == "PASS"]
        # register this round's passes first so same-round co-uploads count
        for u in ups:
            if normalise_verdict(u["verdict"]) == "PASS":
                certified_at.setdefault(rel(u["file"]), rn)
        for u in ups:
            f = rel(u["file"])
            v = normalise_verdict(u["verdict"])
            base_desc = u.get("base") or ""
            base_file = _basefile(base_desc)
            base_rel = rel(base_file) if base_file else None
            row: Dict[str, Any] = {"round": rn, "when": r["when"], "file": f, "verdict": v,
                                   "base": base_rel or base_desc,
                                   "recorded_cause": u.get("recorded_cause"),
                                   "later": u.get("later")}
            if v == "PASS":
                row["class"] = "SURVIVES"
                row["reason"] = ("a PASS is self-certifying" +
                                 (" (deliberate certified control)" if u.get("kind") == "control" else ""))
                rows.append(row)
                continue
            # base status AT THIS ROUND
            if base_rel is None:
                bstat = "undeclared"
            elif base_rel.startswith("samples/"):
                bstat = "sample-source (certified by definition)"
            elif base_rel in failed_at and failed_at[base_rel] <= rn:
                bstat = f"FAILED (round {failed_at[base_rel]})"
            elif base_rel in certified_at and certified_at[base_rel] <= rn:
                bstat = ("certified" if certified_at[base_rel] < rn
                         else "certified this round (co-uploaded PASS)")
            elif base_rel in certified_at:
                bstat = f"certified LATER (round {certified_at[base_rel]})"
            elif base_rel in fails_eventual:
                bstat = f"NEVER certified (itself FAILED later, round {fails_eventual[base_rel]})"
            else:
                bstat = "NEVER certified"
            row["base_status_at_verdict"] = bstat
            row["round_guarded"] = guarded
            row["round_control"] = ("deliberate certified control passed" if deliberate else
                                    ("co-uploaded file(s) PASSED: " + ", ".join(os.path.basename(p) for p in passers))
                                    if guarded else "NONE -- no known-PASS file in the round")
            if bstat.startswith("NEVER") or bstat.startswith("FAILED") or bstat == "undeclared":
                row["class"] = "VOID"
                row["reason"] = f"base {row['base']}: {bstat}"
            elif bstat.startswith("certified LATER"):
                row["class"] = "VOID"
                row["reason"] = f"base {row['base']} was not yet certified at verdict time ({bstat})"
            elif not guarded:
                row["class"] = "UNGUARDED"
                row["reason"] = ("base sound but the round carried NO passing control; oracle "
                                 "health for the window rests on other rounds")
            else:
                row["class"] = "SOUND"
                row["reason"] = f"base {row['base']} {bstat}; {row['round_control']}"
            failed_at.setdefault(f, rn)
            rows.append(row)
    return rows


def render_history(rows: Sequence[dict]) -> str:
    """Markdown table of the retro classification."""
    lines = ["| # | round | file | verdict | base (status at verdict) | control in round | CLASS |",
             "|--:|---|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        base = r.get("base") or ""
        bstat = r.get("base_status_at_verdict", "")
        ctrl = r.get("round_control", "")
        f = os.path.basename(r["file"])
        lines.append(f"| {i} | {r['round']} | `{f}` | {r['verdict']} | "
                     f"`{os.path.basename(str(base)) or base}` {bstat} | {ctrl} | **{r['class']}** |")
    return "\n".join(lines)


def history_summary(rows: Sequence[dict], rounds: Sequence[dict] = HISTORY_ROUNDS) -> dict:
    from collections import Counter
    c = Counter(r["class"] for r in rows)
    fails = [r for r in rows if r["verdict"] == "FAIL"]
    fc = Counter(r["class"] for r in fails)
    passes_by_round = {r["round"]: [os.path.basename(u["file"]) for u in r["uploads"]
                                   if normalise_verdict(u["verdict"]) == "PASS"]
                       for r in rounds}
    deliberate_by_round = {r["round"]: [os.path.basename(u["file"]) for u in r["uploads"]
                                       if u.get("kind") == "control" and
                                       normalise_verdict(u["verdict"]) == "PASS"]
                           for r in rounds}
    fail_rounds = sorted({r["round"] for r in fails})
    return {"verdicts": len(rows), "by_class": dict(c),
            "fails": len(fails), "fails_by_class": dict(fc),
            "rounds": len(rounds),
            "rounds_with_any_pass": sorted(k for k, v in passes_by_round.items() if v),
            "rounds_with_deliberate_certified_control":
                sorted(k for k, v in deliberate_by_round.items() if v),
            "fail_rounds_with_no_pass":
                [k for k in fail_rounds if not passes_by_round.get(k)]}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _parse_verdict_args(pairs: Sequence[str], json_path: Optional[str]) -> Dict[str, str]:
    out: Dict[str, str] = {}
    if json_path:
        with open(abspath(json_path)) as fh:
            data = json.load(fh)
        if isinstance(data, dict):
            for k, v in data.items():
                out[str(k)] = v if isinstance(v, str) else json.dumps(v)
        elif isinstance(data, list):
            for e in data:
                if isinstance(e, dict) and e.get("file"):
                    out[str(e["file"])] = str(e.get("verdict", "PENDING"))
    for p in pairs:
        if "=" not in p:
            raise SystemExit(f"--verdict expects FILE=PASS|FAIL, got {p!r}")
        k, v = p.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sc = sub.add_parser("check", help="dry-run the gate: print violations, stage nothing")
    sc.add_argument("files", nargs="*")
    sc.add_argument("--candidate-base", action="append", default=[],
                    help="file uploaded FOR certification (exempt from the certified-base rule)")
    sc.add_argument("--manifest", default=None, help="probes.json to resolve bases from")
    sc.add_argument("--json", action="store_true")

    ss = sub.add_parser("stage", help="gate + certified control + stage into experiments/acceptance/")
    ss.add_argument("files", nargs="*")
    ss.add_argument("--candidate-base", action="append", default=[])
    ss.add_argument("--control-from", default=None,
                    help="certified file to copy as the control (default: newest certified on disk)")
    ss.add_argument("--manifest", default=None)
    ss.add_argument("--batch", type=int, default=None, help="batch number (default: next)")
    ss.add_argument("--out-dir", default=ACCEPTANCE)
    ss.add_argument("--note", default="")
    ss.add_argument("--no-copy", action="store_true", help="write the manifest but do not copy probes")
    ss.add_argument("--json", action="store_true")

    sr = sub.add_parser("resolve", help="print each file's resolved base + ledger status")
    sr.add_argument("files", nargs="+")
    sr.add_argument("--manifest", default=None)

    sv = sub.add_parser("verdicts", help="interpret a round from its batch_<n>.json + verdicts")
    sv.add_argument("batch_json")
    sv.add_argument("--verdict", action="append", default=[], help="FILE=PASS|FAIL (repeatable)")
    sv.add_argument("--verdicts-json", default=None, help="{file: verdict} JSON")
    sv.add_argument("--json", action="store_true")

    sh = sub.add_parser("retro", help="replay the recorded history through the same rules")
    sh.add_argument("--json", action="store_true")

    args = ap.parse_args(argv)

    if args.cmd in ("check", "stage"):
        ledger = Ledger.load()
        if args.cmd == "check":
            entries, violations = check_batch(args.files, ledger,
                                              candidate_bases=args.candidate_base,
                                              manifest_override=args.manifest)
            if args.json:
                print(json.dumps({"entries": [e.to_json() for e in entries],
                                  "violations": violations,
                                  "admissible": not violations}, indent=1))
            else:
                for e in entries:
                    b = e.base.base if e.base else None
                    st = e.base_status
                    if (e.base_entry or {}).get("aliased_from"):
                        st += f"; certified as {e.base_entry.get('file')} by sha256"
                    elif e.base and e.base.digest_matched:
                        st += "; pinned base recognised by sha256"
                    print(f"  {e.kind:14s} {e.file}\n"
                          f"      base = {b}  [{st}]"
                          + (f"\n      declared by {e.base.source}" if e.base else ""))
                ctrl = ledger.control_source(batch_release(entries, ledger)) or "NONE AVAILABLE"
                if violations:
                    print("\nBATCH REFUSED -- %d violation(s):" % len(violations))
                    for v in violations:
                        print("  * " + v)
                    print("\n(the gate would also add 1 certified control: %s)" % ctrl)
                else:
                    print("\nADMISSIBLE -- `stage` will add the certified control "
                          "(source: %s) and write the manifest" % ctrl)
            return 0 if not violations else 2
        try:
            man = stage_batch(args.files, candidate_bases=args.candidate_base,
                              control_from=args.control_from, out_dir=args.out_dir,
                              batch_n=args.batch, manifest_override=args.manifest,
                              copy=not args.no_copy, ledger=ledger, note=args.note)
        except GateRefusal as gr:
            print(str(gr), file=sys.stderr)
            return 2
        if args.json:
            print(json.dumps(man, indent=1))
        else:
            print(f"batch {man['batch']} staged -> {man['manifest_path']}")
            print("reading order (control FIRST):")
            for e in man["entries"]:
                extra = (f"copy of {e.get('control_source')}" if e["kind"] == "control"
                         else f"base={e.get('base')} [{e.get('base_status', 'candidate')}]")
                print(f"  {e['order']}. {e['kind']:14s} {e['file']}  {extra}")
                if e.get("advisory"):
                    print(f"       ADVISORY: {e['advisory']}")
        return 0

    if args.cmd == "resolve":
        ledger = Ledger.load()
        for f in args.files:
            br = resolve_base(f, args.manifest, ledger.pins)
            st, entry = ledger.status(br.base) if br.base else ("undeclared", None)
            print(json.dumps({**br.to_json(), "ledger_status": st,
                              "ledger_entry": entry}, indent=1))
        return 0

    if args.cmd == "verdicts":
        with open(abspath(args.batch_json)) as fh:
            man = json.load(fh)
        man.setdefault("manifest_path", rel(args.batch_json))
        verdicts = _parse_verdict_args(args.verdict, args.verdicts_json)
        res = read_batch_verdicts(man, verdicts)
        outp = os.path.splitext(abspath(args.batch_json))[0] + ".verdicts.json"
        with open(outp, "w") as fh:
            json.dump({"input_verdicts": verdicts, "interpretation": res}, fh, indent=1)
        if args.json:
            print(json.dumps(res, indent=1))
        else:
            print(f"round status: {res['status']}\n{res['message']}\n")
            for c in res["control_results"]:
                print(f"  CONTROL {c['file']}: {c['verdict']}")
            for p in res["per_file"]:
                print(f"  {p.get('kind', '?'):14s} {p['file']}: {p.get('reading')}")
            if res["actions"]:
                print("actions:\n  - " + "\n  - ".join(res["actions"]))
            print(f"\n(written {rel(outp)})")
        return 0

    if args.cmd == "retro":
        rows = classify_history()
        if args.json:
            print(json.dumps({"rows": rows, "summary": history_summary(rows)}, indent=1))
        else:
            print(render_history(rows))
            print()
            print(json.dumps(history_summary(rows), indent=1))
        return 0
    return 1


if __name__ == "__main__":
    sys.exit(main())
