"""Decoders for `Global/PartitionTable` and `Partitions/<N>` streams.

See docs/streams/05-partitions.md for the derived layouts, worked
examples and confidence levels.  Everything below is verified byte-for-byte
against the six Revit 2026 samples unless marked [hypothesis].

Global/PartitionTable (inflated, 87-179 bytes) -- a *workset* table
    u16   class ordinal 0x0c80 (3200)                   [hypothesis: name]
    u32   version = 1
    u32   entry_count (= 1 in every sample: only the default workset)
    entry_count x
        16B  GUID   (workset unique id; the 4 template-born files share
                     {E3E052F8-0156-11D5-9301-0000863F27AD})
        u32  0
        u32  id_a   (352 / 254 / 131 -- per file)
        u32  id_b   (824 / 596 / 776 / 556 / 989 / 2654 -- per file)
        i32  -1
        u32  kind   (0 user workset, 1 "Project Standards", 2 "Family : ...")
        u8   0
        u32  name_len + UTF-16LE name
        u32 1, u32 1, u32 0, u32 1, u32 0

STREAM PAGING (applies to EVERY OLE stream, not just Partitions):
    the raw stream bytes are stored in 64,896-byte pages, each full page
    followed by a 353-byte page-trailer record (opaque, high entropy, first
    byte always 0x00).  De-page first (`depage()`); everything below is in
    de-paged ("clean") offsets.  raw_off = clean_off + 353 * (clean_off // 64896).

Partitions/<N> (de-paged; NOT gzip at offset 0)
    Stream header (18 bytes)
        u32  9                 -- record/format version (constant)
        u32  0
        u16  0x3a3             -- container class ordinal [hypothesis]
        i32  0
        u32  elem_table_count  == count field of Global/ElemTable
    then 1..n "save units", each a run of framed compressed blocks
        block:
            u16  0x0f28 (3880)  block header tag
            u32  flags          4 = whole records only, 6 = last record
                                continues into the next block, 7 = pure
                                continuation, 5 = starts inside a spanning
                                record that ends here (bit2 always set,
                                bit1 = "record continues", bit0 =
                                "continues previous")
            u32  A  n_records   record headers that START in this block
            u32  B  size_hint   = 8 + gzip member length (bytes from the seq
                                field to the member end); mirrored in the
                                trailer.  100 % after de-paging.
            u32  C  body_bytes  record body bytes stored in this block
                                (ISIZE == hdr_len(seq)*A + C + adj(flags),
                                 hdr_len = 16 for seq 101, 20 for 102/103,
                                 adj = {4: 0, 5: +4, 6: -4, 7: 0})
            u32  seq            101 / 102 / 103 -- logical sub-stream id
            u32  0
            gzip member         1f 8b 08 00 00 00 00 00 00 0b + raw deflate +
                                (crc32, isize); the trailer VALIDATES for
                                every block once the stream is de-paged
            u16  0x0f21 (3873)  trailer tag
            u32  B              copy of the header's B
        unit terminator + footer:
            u16  0x0f28 + u32 0 + u32 0 + u32 0 + u32 0     (18 bytes)
            u16  0x0f3f (3903) + u32 blob_len + blob (0 or 64 opaque bytes)
            u32  n + UTF-16LE string "Data generated by Autodesk(R) Revit(R)"
                 (n = 0 in the tiny dach Partitions/85)
        unit separator (28 bytes, precedes the next unit's first block):
            u16 0x3a3, i32 -1, u16 0x3a2, u32 counter, 16B GUID
            (the GUID also appears in Global/Latest and Global/
             ContentDocuments -> save/episode identity)
    stream end record (after the last footer):
        u16 0x3a3, i32 0, i32 -1, u32 0, zero padding (0-484 bytes),
        opaque high-entropy tail (48-276 bytes)             [undecoded]

Record framing inside the concatenated per-seq byte stream:
    seq 101      16-byte header { i64 id, u32 body_size, u32 cls } + body
                 (cls == 0x5e5 = 1509 for essentially every record)
    seq 102/103  20-byte header { i64 id, u32 stamp, u32 body_size, u32 cls }
                 + body
    A record whose body spans blocks (flags 6/7/5 chain) is closed by a u32
    repeat of body_size after its last body byte.
"""
from __future__ import annotations

import os
import struct
import sys
import zlib
from collections import Counter
from dataclasses import dataclass, field
from typing import Dict, Iterator, List, Optional, Tuple

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EXTRACTED = os.path.join(ROOT, 'extracted')

SAMPLES = [
    'racbasicsampleproject',
    'racadvancedsampleproject',
    'rmebasicsampleproject',
    'rstadvancedsampleproject',
    'rstbasicsampleproject',
    'dach-sample-project',
]

BLOCK_TAG = 0x0F28       # 3880 block header marker
TRAILER_TAG = 0x0F21     # 3873 block trailer marker
FOOTER_TAG = 0x0F3F      # 3903 footer blob marker
CONTAINER_CLASS = 0x3A3  # 931  stream header / unit separator / end record
UNIT_INNER_CLASS = 0x3A2  # 930  inside the unit separator
PT_CLASS = 0x0C80        # 3200 class ordinal leading Global/PartitionTable

RECORD_HDR_101 = 16      # i64 id, u32 size, u32 cls
RECORD_HDR_10X = 20      # i64 id, u32 stamp, u32 size, u32 cls

TERMINATOR = struct.pack('<HIIII', BLOCK_TAG, 0, 0, 0, 0)  # 18 bytes

# stream paging: every OLE stream is written as 64,896-byte pages, each
# full page followed by a 353-byte page trailer that must be excised before
# any gzip member is inflated (verified: 100 % gzip CRC/ISIZE match after)
PAGE_SIZE = 64896        # 0xFD80 payload bytes per page
PAGE_TRAILER = 353       # opaque per-page record (first byte 0x00)
PAGE_STRIDE = PAGE_SIZE + PAGE_TRAILER  # 65249

_ISIZE_ADJ = {4: 0, 5: 4, 6: -4, 7: 0}


def depage(raw: bytes) -> Tuple[bytes, List[bytes]]:
    """Remove the 353-byte page trailers. Returns (clean_bytes, trailers)."""
    if len(raw) <= PAGE_SIZE:
        return raw, []
    out = bytearray()
    trailers: List[bytes] = []
    pos = 0
    n = len(raw)
    while pos < n:
        out += raw[pos:pos + PAGE_SIZE]
        if pos + PAGE_SIZE < n:
            trailers.append(raw[pos + PAGE_SIZE:pos + PAGE_STRIDE])
        pos += PAGE_STRIDE
    return bytes(out), trailers


def clean_to_raw_offset(clean_off: int) -> int:
    """Map an offset in the de-paged stream back to the raw OLE stream."""
    return clean_off + PAGE_TRAILER * (clean_off // PAGE_SIZE)


# ---------------------------------------------------------------------------
# Global/PartitionTable
# ---------------------------------------------------------------------------

@dataclass
class PartitionTableEntry:
    guid: bytes
    zero0: int
    id_a: int
    id_b: int
    minus_one: int
    kind: int
    name: str
    tail: Tuple[int, ...]

    def guid_str(self) -> str:
        return fmt_guid(self.guid)


@dataclass
class PartitionTable:
    class_ordinal: int
    version: int
    count: int
    entries: List[PartitionTableEntry]
    trailing: bytes

    def dump(self) -> str:
        lines = [f'PartitionTable class=0x{self.class_ordinal:04x} version={self.version} count={self.count}']
        for i, e in enumerate(self.entries):
            lines.append(
                f'  [{i}] guid={e.guid_str()} zero0={e.zero0} id_a={e.id_a} id_b={e.id_b} '
                f'minus_one={e.minus_one} kind={e.kind} name={e.name!r} tail={e.tail}')
        if self.trailing:
            lines.append(f'  trailing {len(self.trailing)} bytes: {self.trailing.hex(" ")}')
        return '\n'.join(lines)


def fmt_guid(g: bytes) -> str:
    d1, d2, d3 = struct.unpack('<IHH', g[:8])
    d4 = g[8:16]
    return f'{{{d1:08X}-{d2:04X}-{d3:04X}-{d4[:2].hex().upper()}-{d4[2:].hex().upper()}}}'


def parse_partition_table(buf: bytes) -> PartitionTable:
    """Parse the inflated Global/PartitionTable payload."""
    cls, version, count = struct.unpack_from('<HII', buf, 0)
    if cls != PT_CLASS:
        raise ValueError(f'unexpected PartitionTable class ordinal 0x{cls:x}')
    p = 10
    entries: List[PartitionTableEntry] = []
    for _ in range(count):
        guid = buf[p:p + 16]
        p += 16
        zero0, id_a, id_b, minus_one, kind = struct.unpack_from('<IIIiI', buf, p)
        p += 20
        flag = buf[p]           # u8, 0 in every sample
        p += 1
        (nchars,) = struct.unpack_from('<I', buf, p)
        p += 4
        name = buf[p:p + 2 * nchars].decode('utf-16-le')
        p += 2 * nchars
        tail_words = struct.unpack_from('<IIIII', buf, p)   # 1, 1, 0, 1, 0
        p += 20
        entries.append(PartitionTableEntry(guid, zero0, id_a, id_b, minus_one, kind,
                                           name, (flag,) + tail_words))
    return PartitionTable(cls, version, count, entries, buf[p:])


def load_partition_table(project: str) -> PartitionTable:
    path = os.path.join(EXTRACTED, project, 'Global__PartitionTable.gz', '000.bin')
    with open(path, 'rb') as fh:
        return parse_partition_table(fh.read())


# ---------------------------------------------------------------------------
# Partitions/<N> framing
# ---------------------------------------------------------------------------

@dataclass
class StreamHeader:
    version: int          # 9
    zero0: int            # 0
    class_ordinal: int    # 0x3a3
    zero1: int            # 0 (i32)
    elem_table_count: int  # == Global/ElemTable count field
    size: int = 18

    def dump(self) -> str:
        return (f'stream header: version={self.version} zero0={self.zero0} '
                f'class=0x{self.class_ordinal:x} zero1={self.zero1} '
                f'elem_table_count={self.elem_table_count}')


def parse_stream_header(raw: bytes) -> StreamHeader:
    version, zero0, cls, zero1, cnt = struct.unpack_from('<IIHiI', raw, 0)
    if version != 9 or cls != CONTAINER_CLASS:
        raise ValueError(f'unexpected Partitions header: v={version} cls=0x{cls:x}')
    return StreamHeader(version, zero0, cls, zero1, cnt)


@dataclass
class Block:
    index: int
    unit: int              # save-unit index (0 = original save)
    hdr_offset: int        # offset of the u16 0x0f28 tag
    flags: int             # 4/5/6/7
    n_records: int         # A
    size_hint: int         # B
    body_bytes: int        # C
    seq: int               # 101/102/103
    z: int                 # 0
    member_offset: int     # offset of the gzip magic
    member_len: int        # physical gzip member bytes (up to trailer tag)
    trailer_ok: bool       # trailer marker found where B says (member+8 == B)
    data: Optional[bytes] = None
    crc_ok: Optional[bool] = None      # gzip (crc32, isize) validates our output
    isize: Optional[int] = None        # ISIZE stored in the gzip trailer

    @property
    def intended_len(self) -> int:
        """Uncompressed length implied by the header (== gzip ISIZE).

        hdr_len(seq)*A + C, with a +/-4 adjustment for the u32 size-repeat
        that closes a block-spanning record: flags 6 (record starts here and
        continues) -> -4, flags 5 (spanning record ends here) -> +4,
        flags 4 / 7 -> 0.  Exact on all 13,535 blocks of the corpus.
        """
        return (record_header_len(self.seq) * self.n_records + self.body_bytes
                + _ISIZE_ADJ.get(self.flags, 0))

    def brief(self) -> str:
        return (f'blk{self.index:5d} u{self.unit:3d} @0x{self.hdr_offset:08x} '
                f'flags={self.flags} A={self.n_records:5d} B={self.size_hint:6d} '
                f'C={self.body_bytes:7d} seq={self.seq} member={self.member_len:6d} '
                f'infl={len(self.data) if self.data is not None else "?"} '
                f'crc_ok={self.crc_ok} intended={self.intended_len}')


@dataclass
class Unit:
    index: int
    first_block: int
    n_blocks: int = 0
    guid: Optional[bytes] = None       # from the separator preceding this unit
    counter: Optional[int] = None      # u32 in the separator
    footer_offset: Optional[int] = None
    footer_blob: bytes = b''
    footer_text: str = ''
    prefix_blob: bytes = b''   # opaque bytes between separator and first block


def _inflate_member(raw: bytes, start: int, end: int) -> Tuple[bytes, bool, int]:
    """Inflate a gzip member occupying raw[start:end] (incl. 10B hdr, 8B trailer).

    Returns (data, crc_ok, stored_isize).  Uses raw inflate; the stored gzip
    trailer validates our output only for ~83 % of members.
    """
    body = raw[start + 10:end - 8]
    stored_crc, stored_isize = struct.unpack_from('<II', raw, end - 8)
    d = zlib.decompressobj(-zlib.MAX_WBITS)
    try:
        out = d.decompress(body) + d.flush()
    except zlib.error:
        return b'', False, stored_isize
    crc_ok = (zlib.crc32(out) & 0xFFFFFFFF) == stored_crc and \
        (len(out) & 0xFFFFFFFF) == stored_isize
    return out, crc_ok, stored_isize


def _find_block_header(raw: bytes, start: int, limit: int = 65536) -> int:
    """Find the next plausible block header (0x0f28 with flags in 4..7)."""
    end = min(len(raw), start + limit)
    q = start
    while True:
        q = raw.find(b'\x28\x0f', q, end)
        if q < 0:
            return -1
        if q + 26 <= len(raw):
            flags = struct.unpack_from('<I', raw, q + 2)[0]
            if flags in (4, 5, 6, 7) and raw[q + 26:q + 29] == b'\x1f\x8b\x08':
                return q
        q += 1


class StreamWalker:
    """Walks the physical framing: header, units, blocks, footers, end record."""

    def __init__(self, raw: bytes, inflate: bool = True, keep_data: bool = True):
        self.raw = raw
        self.inflate = inflate
        self.keep_data = keep_data
        self.header = parse_stream_header(raw)
        self.blocks: List[Block] = []
        self.units: List[Unit] = []
        self.end_offset: int = 0          # offset of the stream end record
        self.end_record: bytes = b''
        self.errors: List[str] = []
        self._walk()

    def _walk(self) -> None:
        raw = self.raw
        n = len(raw)
        pos = self.header.size
        unit = Unit(index=0, first_block=0)
        self.units.append(unit)
        while pos + 2 <= n:
            (tag,) = struct.unpack_from('<H', raw, pos)
            if tag == BLOCK_TAG and raw[pos:pos + 18] == TERMINATOR:
                # unit footer
                pos = self._read_footer(unit, pos)
                if pos < 0:
                    return
                # what follows: unit separator (a3 03 -1 a2 03 ...) or end record
                if raw[pos:pos + 6] == struct.pack('<Hi', CONTAINER_CLASS, -1) \
                        and struct.unpack_from('<H', raw, pos + 6)[0] == UNIT_INNER_CLASS:
                    counter = struct.unpack_from('<I', raw, pos + 8)[0]
                    guid = raw[pos + 12:pos + 28]
                    pos += 28
                    unit = Unit(index=len(self.units), first_block=len(self.blocks),
                                guid=guid, counter=counter)
                    self.units.append(unit)
                    if raw[pos:pos + 2] != struct.pack('<H', BLOCK_TAG):
                        # tolerate unexpected bytes between a separator and
                        # the next block header (never seen after de-paging)
                        nxt = _find_block_header(raw, pos)
                        if nxt < 0:
                            self.end_offset = pos
                            self.end_record = raw[pos:]
                            return
                        unit.prefix_blob = raw[pos:nxt]
                        self.errors.append(f'skipped {nxt-pos} bytes after separator at {pos}')
                        pos = nxt
                    continue
                # end record
                self.end_offset = pos
                self.end_record = raw[pos:]
                return
            if tag != BLOCK_TAG:
                self.errors.append(f'unexpected tag 0x{tag:04x} at {pos}')
                self.end_offset = pos
                self.end_record = raw[pos:]
                return
            _tag, flags, A, B, C, seq, z = struct.unpack_from('<HIIIIII', raw, pos)
            member = pos + 26
            trailer_pat = struct.pack('<HI', TRAILER_TAG, B)
            guess = member + B - 8
            if guess + 6 <= n and raw[guess:guess + 6] == trailer_pat:
                end = guess
                trailer_ok = True
            else:
                end = raw.find(trailer_pat, member)
                trailer_ok = False
                if end < 0:
                    self.errors.append(f'no trailer for block at {pos} (B={B})')
                    self.end_offset = pos
                    self.end_record = raw[pos:]
                    return
            blk = Block(len(self.blocks), unit.index, pos, flags, A, B, C, seq, z,
                        member, end - member, trailer_ok)
            if self.inflate:
                data, ok, isize = _inflate_member(raw, member, end)
                blk.crc_ok, blk.isize = ok, isize
                blk.data = data if self.keep_data else None
                blk._len = len(data)  # type: ignore[attr-defined]
            self.blocks.append(blk)
            unit.n_blocks += 1
            pos = end + 6
        # walked off the end without an end record
        self.end_offset = pos
        self.end_record = raw[pos:]

    def _read_footer(self, unit: Unit, pos: int) -> int:
        raw = self.raw
        unit.footer_offset = pos
        p = pos + 18
        if p + 6 > len(raw) or struct.unpack_from('<H', raw, p)[0] != FOOTER_TAG:
            self.errors.append(f'footer tag missing at {p}')
            self.end_offset = pos
            self.end_record = raw[pos:]
            return -1
        (blen,) = struct.unpack_from('<I', raw, p + 2)
        unit.footer_blob = raw[p + 6:p + 6 + blen]
        p += 6 + blen
        (nchars,) = struct.unpack_from('<I', raw, p)
        p += 4
        unit.footer_text = raw[p:p + 2 * nchars].decode('utf-16-le', 'replace')
        return p + 2 * nchars


def iter_blocks(raw: bytes, inflate: bool = True) -> Iterator[Block]:
    """Yield every framed block of a raw Partitions/<N> stream, in order."""
    yield from StreamWalker(raw, inflate=inflate).blocks


# ---------------------------------------------------------------------------
# Element record layer
# ---------------------------------------------------------------------------

@dataclass
class RecordHeader:
    offset: int      # offset within the buffer walked
    elem_id: int
    stamp: Optional[int]   # only for seq 102/103 headers
    body_size: int
    cls: int
    hdr_len: int


def record_header_len(seq: int) -> int:
    return RECORD_HDR_101 if seq == 101 else RECORD_HDR_10X


def parse_record_header(buf: bytes, p: int, seq: int) -> RecordHeader:
    if seq == 101:
        eid, size, cls = struct.unpack_from('<qII', buf, p)
        return RecordHeader(p, eid, None, size, cls, RECORD_HDR_101)
    eid, stamp, size, cls = struct.unpack_from('<qIII', buf, p)
    return RecordHeader(p, eid, stamp, size, cls, RECORD_HDR_10X)


def scan_element_headers(buf: bytes, seq: int, limit: Optional[int] = None) -> Iterator[RecordHeader]:
    """Iterate record headers over a segment buffer produced by
    PartitionStream.concat_segment (size-repeats already removed).

    Stops when a header no longer looks plausible (id or size out of range).
    """
    hlen = record_header_len(seq)
    p = 0
    n = len(buf)
    count = 0
    while p + hlen <= n:
        rh = parse_record_header(buf, p, seq)
        if not (-1 <= rh.elem_id < (1 << 40)) or rh.body_size > (1 << 30):
            return
        yield rh
        count += 1
        if limit and count >= limit:
            return
        p += hlen + rh.body_size


# ---------------------------------------------------------------------------
# High level
# ---------------------------------------------------------------------------

@dataclass
class PartitionStream:
    project: str
    name: str
    raw_size: int
    clean_size: int
    n_pages: int
    header: StreamHeader
    blocks: List[Block]
    units: List[Unit]
    end_offset: int          # clean (de-paged) offset
    end_record: bytes
    errors: List[str]
    page_trailers: List[bytes] = field(default_factory=list)

    def blocks_by_seq(self) -> Dict[int, List[Block]]:
        out: Dict[int, List[Block]] = {}
        for b in self.blocks:
            out.setdefault(b.seq, []).append(b)
        return out

    def concat_segment(self, seq: int) -> bytes:
        """Concatenate inflated payloads of one sub-stream (seq) in stream order.

        Pure concatenation of block payloads reconstructs the segment as a
        contiguous sequence of records [header][body][header][body]... --
        records that span blocks join up seamlessly (verified: the next record
        header follows the spanning body immediately).
        """
        return b''.join(b.data for b in self.blocks if b.seq == seq and b.data)


def partition_stream_paths(project: str) -> List[str]:
    d = os.path.join(EXTRACTED, project)
    return sorted(
        os.path.join(d, fn) for fn in os.listdir(d)
        if fn.startswith('Partitions__') and fn.endswith('.bin')
        # exclude the de-paged .logical.bin artefact written by
        # tools/build_corpus.py, which would otherwise be walked twice
        # (object-decoder found this produced phantom duplicate records)
        and not fn.endswith('.logical.bin')
    )


def load_stream(path: str, inflate: bool = True, keep_data: bool = True) -> PartitionStream:
    """Load a Partitions/<N> stream: de-page, then walk the framing."""
    with open(path, 'rb') as fh:
        raw = fh.read()
    clean, trailers = depage(raw)
    w = StreamWalker(clean, inflate=inflate, keep_data=keep_data)
    project = path.split(os.sep)[-2]
    return PartitionStream(project, os.path.basename(path)[:-4], len(raw), len(clean),
                           len(trailers) + 1, w.header, w.blocks, w.units,
                           w.end_offset, w.end_record, w.errors, trailers)


def concat_elements(project: str = 'racbasicsampleproject', seq: int = 101) -> bytes:
    """Joined element-data buffer for one sub-stream across a project's partitions."""
    parts = []
    for p in partition_stream_paths(project):
        parts.append(load_stream(p).concat_segment(seq))
    return b''.join(parts)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def _fmt_counter(c: Counter, top: int = 8) -> str:
    return ', '.join(f'{k}:{v}' for k, v in c.most_common(top))


def block_length(b: Block) -> Optional[int]:
    if b.data is not None:
        return len(b.data)
    return getattr(b, '_len', None)


def report_stream(path: str, deep: bool = True, sample_records: int = 3) -> None:
    s = load_stream(path, keep_data=deep)
    print(f'\n=== {s.project} / {s.name}  ({s.raw_size:,} raw bytes -> '
          f'{s.clean_size:,} after removing {s.n_pages-1} page trailers)')
    print('  ' + s.header.dump())
    nblk = len(s.blocks)
    crc_ok = sum(1 for b in s.blocks if b.crc_ok)
    seqc = Counter(b.seq for b in s.blocks)
    flagc = Counter(b.flags for b in s.blocks)
    print(f'  units={len(s.units)}  blocks={nblk}  gzip-trailer-valid={crc_ok} '
          f'({100.0*crc_ok/max(nblk,1):.1f}%)  seq={dict(sorted(seqc.items()))}  '
          f'flags={dict(sorted(flagc.items()))}')
    b_len = sum(1 for b in s.blocks if b.trailer_ok)
    lin = sum(1 for b in s.blocks if block_length(b) == b.intended_len)
    isz = sum(1 for b in s.blocks if b.isize == b.intended_len)
    print(f'  B==8+member: {b_len}/{nblk}   ISIZE==hdrlen*A+C+adj: {isz}/{nblk}   '
          f'inflated==intended: {lin}/{nblk}')
    total = sum(block_length(b) or 0 for b in s.blocks)
    print(f'  inflated total = {total:,} bytes; end record @{s.end_offset} '
          f'({len(s.end_record)} bytes); errors={s.errors[:2]}')
    if s.units:
        u0, ul = s.units[0], s.units[-1]
        print(f'  unit0: blocks={u0.n_blocks} footer_blob={len(u0.footer_blob)}B '
              f'text={u0.footer_text[:30]!r}')
        if len(s.units) > 1:
            u1 = s.units[1]
            print(f'  unit1: guid={fmt_guid(u1.guid) if u1.guid else None} '
                  f'counter={u1.counter} blocks={u1.n_blocks}')
            print(f'  last unit {ul.index}: guid={fmt_guid(ul.guid) if ul.guid else None} '
                  f'counter={ul.counter} blocks={ul.n_blocks}')
    for b in s.blocks[:3]:
        print('   ' + b.brief())
    if not deep or not s.blocks:
        return
    for seq in sorted(seqc):
        seg = s.concat_segment(seq)
        cls: Counter = Counter()
        ids = set()
        nrec = 0
        endp = 0
        for rh in scan_element_headers(seg, seq):
            nrec += 1
            cls[rh.cls & 0xFFFF] += 1
            ids.add(rh.elem_id)
            endp = rh.offset + rh.hdr_len + rh.body_size
        walk_ok = endp == len(seg)
        print(f'   seq {seq}: {seqc[seq]} blocks -> segment {len(seg):,} bytes; '
              f'record walk covers {endp:,} ({"COMPLETE" if walk_ok else "PARTIAL"}); '
              f'{nrec:,} records, {len(ids):,} distinct ids; top cls: {_fmt_counter(cls, 6)}')
        shown = 0
        for rh in scan_element_headers(seg, seq, limit=sample_records):
            stamp = f' stamp=0x{rh.stamp:08x}' if rh.stamp is not None else ''
            body = seg[rh.offset + rh.hdr_len:rh.offset + rh.hdr_len + 20]
            print(f'      rec id={rh.elem_id} size={rh.body_size} cls=0x{rh.cls:x}'
                  f'{stamp} body[:20]={body.hex(" ")}')
            shown += 1


def main(argv: List[str]) -> int:
    projects = [a for a in argv if not a.startswith('-')] or SAMPLES
    deep = '--shallow' not in argv
    print('#### Global/PartitionTable ####')
    for proj in SAMPLES:
        try:
            pt = load_partition_table(proj)
        except FileNotFoundError:
            continue
        print(f'--- {proj}')
        print(pt.dump())
    print('\n#### Partitions/<N> ####')
    for proj in projects:
        for path in partition_stream_paths(proj):
            report_stream(path, deep=deep)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
