"""schema_b — STRUCTURAL/STATISTICAL decode of the Revit `Formats/Latest`
schema stream (method B, independent cross-validation for schema-a).

Method: no external knowledge of the format is assumed.  The grammar below
was derived purely from (1) length-prefixed identifier harvesting, (2)
record-boundary alignment (records tile the byte stream exactly), and (3)
gap statistics between consecutive field names, which reveal the byte
length of every field-descriptor tag.  Scalar type codes are calibrated
statistically: the schema defines synthetic template classes named e.g.
``std::pair< ElementId, int >`` whose ``second`` field descriptor is the
tag for C++ ``int`` — a ground truth generated by the format itself.

Derived grammar (all little-endian; see docs/streams/01-schema-b.md):

    stream      := record*                       (top-level classes, alphabetical)
    record      := u16 marker(=0) u16 nameLen name[nameLen]
                   u16 baseRef                   (0 = none; 0x8000|ord = inline
                                                  definition of the base follows
                                                  as a nested record)
                   [record if baseRef & 0x8000]
                   u32 version u32 fieldCount
                   field[fieldCount]
                   u32 nGuid guid[nGuid]         (16-byte GUIDs; usually 0)
    field       := u32 nameLen name[nameLen] typedesc
    typedesc    := u8 kind u8 mod u16 zero
                   kind==0x0e (class):  mod in {00,50,..}: u16 ref [record if flagged]
                                        mod == 10:        u32 count u16 ref [record]
                                        mod == 11:        u32 count            (ptr array)
                                        mod in {01,02,03,51}: nothing        (pointers)
                   kind==0x0d (typed):  [mod==10: u32 count] u32 k u8 sep typedesc [u16 ref]
                   other kinds:         mod==10: u32 count ; else nothing

Class ordinals: a reference with the high bit set (0x8000|N) means "class N
is defined right here, inline"; classes are numbered in definition order
starting at 12 (ordinals 0..11 are reserved — [hypothesis] built-in kinds).
The parser verifies this: every flagged reference equals 12 + index.

IMPORTANT LIMITATION (see the doc): the inflated stream is byte-faithful
for its first ~0x21e5c bytes (through record ~1150, class names A..DDG,
alphabetical) and is scrambled beyond that point — a decade-old writer-side
defect present identically in every Revit release we could test.  This
module decodes the faithful prefix exhaustively and *characterises* the
degraded remainder rather than pretending to parse it.

Output: ``extracted/_schema/schema_b.json``.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import struct
import sys
import zlib
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SAMPLES = [
    "racbasicsampleproject", "racadvancedsampleproject", "rmebasicsampleproject",
    "rstadvancedsampleproject", "rstbasicsampleproject", "dach-sample-project",
]
DEFAULT_STREAM = os.path.join(
    ROOT, "extracted", "racbasicsampleproject", "Formats__Latest.gz", "000.bin")
OUT_JSON = os.path.join(ROOT, "extracted", "_schema", "schema_b.json")

ORDINAL_BASE = 12          # first user class = ordinal 12 (verified below)
IDENT_RE = re.compile(rb"[A-Za-z_][A-Za-z0-9_:<>*&,~ ]*$")

# --- primitive-kind codebook (low byte of the descriptor tag) --------------
# Calibrated statistically from std::pair<> synthetic classes (ground truth)
# plus field-name/value statistics; confidence noted per entry.
KIND_NAMES = {
    0x00: "?kind00",
    0x01: "bool",            # ground truth: std::pair< X, bool >.second
    0x02: "?short/enum16",   # m_flags, m_constrFlags, enum m_typeOfChange  [hypothesis]
    0x03: "?long/enum32",    # UserID.m_id, m_nAtomType, m_viewerFlags       [hypothesis]
    0x04: "int",             # ground truth: std::pair< X, int > (unsigned int also maps here)
    0x05: "unsigned long",   # ground truth: std::pair< unsigned long, X >; ATime.m_msb/m_lsb, m_color
    0x06: "float",           # APropertyFloat.m_value                         [strong]
    0x07: "double",          # ground truth: std::pair< X, double >
    0x08: "AString",         # ground truth: std::pair< X, AString > (always mod 0x60)
    0x09: "GUID",            # GUIDvalue.m_guid
    0x0a: "?classref",      # ClassDefinitionRef.m_ref                        [hypothesis]
    0x0b: "Int64",           # Identifier.m_id64, m_hashNative                [strong]
    0x0c: "?kind0c",
    0x0d: "wrapped",         # array/vector wrapper carrying a nested typedesc
    0x0e: "class",           # user class; a u16 class reference follows
}
# modifier (high byte)
MOD_NAMES = {
    0x00: "value",
    0x01: "ptr",             # pointer flavour 1 (polymorphic object)   [hypothesis]
    0x02: "ptr_owned",       # m_elemTable / m_pAppInfoManager        [hypothesis]
    0x03: "ptr_back",        # m_pACD / m_pADoc (back/weak pointer)    [hypothesis]
    0x10: "array",           # fixed-length array, u32 count
    0x11: "ptrarray",        # fixed-length array of pointers, u32 count
    0x40: "?mod40",
    0x50: "container",       # growable container (vector/set/map-of-pairs)
    0x51: "ptrcontainer",    # container of pointers
    0x52: "?mod52",
    0x60: "str",             # only ever seen with kind 0x08 (AString)
    0x61: "?mod61",
    0x62: "?mod62",
}


class ParseError(Exception):
    pass


class Reader:
    __slots__ = ("d", "pos")

    def __init__(self, data: bytes, pos: int = 0):
        self.d = data
        self.pos = pos

    def u8(self) -> int:
        v = self.d[self.pos]
        self.pos += 1
        return v

    def u16(self) -> int:
        v = struct.unpack_from("<H", self.d, self.pos)[0]
        self.pos += 2
        return v

    def u32(self) -> int:
        v = struct.unpack_from("<I", self.d, self.pos)[0]
        self.pos += 4
        return v

    def take(self, k: int) -> bytes:
        v = self.d[self.pos:self.pos + k]
        self.pos += k
        return v


# ---------------------------------------------------------------------------
# grammar
# ---------------------------------------------------------------------------

class SchemaParser:
    def __init__(self, data: bytes):
        self.data = data
        self.records = []          # in definition order (ordinal order)
        self.by_ordinal = {}

    # -- typedesc -----------------------------------------------------------
    def parse_typedesc(self, p: Reader, depth: int) -> dict:
        start = p.pos
        kind = p.u8()
        mod = p.u8()
        x = p.u16()
        desc = {"tag_hex": f"{kind:02x}{mod:02x}", "kind": kind, "mod": mod,
                "x": x, "off": start}
        if x != 0:
            raise ParseError(f"typedesc pad != 0 ({x:#x}) @ {start:#x}")
        if kind == 0x0e:                               # user class
            if mod in (0x00, 0x40, 0x50, 0x52, 0x60, 0x61, 0x62):
                ref = p.u16()
                desc["ref"] = ref
                if ref & 0x8000:
                    self.parse_record(p, depth + 1, expect=ref & 0x7FFF)
            elif mod == 0x10:
                desc["count"] = p.u32()
                ref = p.u16()
                desc["ref"] = ref
                if ref & 0x8000:
                    self.parse_record(p, depth + 1, expect=ref & 0x7FFF)
            elif mod == 0x11:
                desc["count"] = p.u32()
            elif mod in (0x01, 0x02, 0x03, 0x51):
                pass
            else:
                raise ParseError(f"unknown class mod {mod:#x} @ {start:#x}")
        elif kind == 0x0d:                             # wrapped/typed array
            if mod == 0x10:
                desc["count"] = p.u32()
            elif mod != 0x50:
                raise ParseError(f"unknown 0d mod {mod:#x} @ {start:#x}")
            desc["k"] = p.u32()
            desc["sep"] = p.u8()
            desc["inner"] = self.parse_typedesc(p, depth)
            if desc["inner"]["kind"] == 0x0e:
                desc["ref2"] = p.u16()
        else:                                          # scalar kinds
            if mod == 0x10:
                desc["count"] = p.u32()
            elif mod not in (0x00, 0x01, 0x02, 0x03, 0x40, 0x50, 0x51, 0x60):
                raise ParseError(
                    f"unknown scalar tag kind={kind:#x} mod={mod:#x} @ {start:#x}")
        desc["len"] = p.pos - start
        return desc

    # -- record -------------------------------------------------------------
    def parse_record(self, p: Reader, depth: int, expect=None) -> dict:
        start = p.pos
        marker = p.u16()
        if marker != 0:
            raise ParseError(f"expected 0000 record marker @ {start:#x}, got {marker:#06x}")
        name_len = p.u16()
        if not 1 <= name_len <= 300:
            raise ParseError(f"bad class-name length {name_len} @ {p.pos - 2:#x}")
        name = p.take(name_len)
        if not IDENT_RE.match(name):
            raise ParseError(f"bad class name {name[:32]!r} @ {p.pos - name_len:#x}")
        rec = {"offset": start, "name": name.decode("latin1"), "depth": depth,
               "expect": expect, "ordinal": ORDINAL_BASE + len(self.records)}
        # ordinal is assigned by DEFINITION ORDER (name occurrence order);
        # append before descending so nested definitions number after us.
        self.records.append(rec)
        base = p.u16()
        rec["base_ref"] = base
        if base & 0x8000:
            self.parse_record(p, depth + 1, expect=base & 0x7FFF)
        rec["version"] = p.u32()
        fc = p.u32()
        if fc > 5000:
            raise ParseError(f"absurd field count {fc} @ {p.pos - 4:#x}")
        fields = []
        for _ in range(fc):
            flen = p.u32()
            if not 1 <= flen <= 300:
                raise ParseError(f"bad field-name length {flen} @ {p.pos - 4:#x}")
            fname = p.take(flen)
            if not IDENT_RE.match(fname):
                raise ParseError(
                    f"bad field name {fname[:32]!r} @ {p.pos - flen:#x}")
            td = self.parse_typedesc(p, depth)
            fields.append({"name": fname.decode("latin1"), "desc": td})
        rec["fields"] = fields
        nguid = p.u32()
        if nguid > 100000:
            raise ParseError(f"absurd trailer guid count {nguid} @ {p.pos - 4:#x}")
        rec["trailer_guids"] = [format_guid(p.take(16)) for _ in range(nguid)]
        rec["end"] = p.pos
        return rec

    # -- driver ---------------------------------------------------------------
    def parse(self):
        """Parse records until the grammar breaks; return (clean_end, error)."""
        p = Reader(self.data)
        clean_end = 0
        err = None
        n = len(self.data)
        while p.pos < n:
            try:
                self.parse_record(p, 0)
                clean_end = p.pos
            except (ParseError, struct.error, IndexError) as ex:
                err = f"{type(ex).__name__}: {ex}"
                # drop the partial record that failed
                while self.records and "end" not in self.records[-1]:
                    self.records.pop()
                break
        self.by_ordinal = {r["ordinal"]: r for r in self.records}
        self.clean_end = clean_end
        self.error = err
        return clean_end, err


def format_guid(b: bytes) -> str:
    # standard mixed-endian GUID rendering (data1..3 little-endian)
    d1, d2, d3 = struct.unpack("<IHH", b[:8])
    return f"{d1:08x}-{d2:04x}-{d3:04x}-{b[8:10].hex()}-{b[10:16].hex()}"


# ---------------------------------------------------------------------------
# type-string rendering + statistics
# ---------------------------------------------------------------------------

def type_string(desc: dict, by_ordinal: dict) -> str:
    kind = desc["kind"]
    mod = desc["mod"]
    if kind == 0x0e:
        base = "?ptr" if mod in (0x01, 0x02, 0x03, 0x51, 0x11) else "?"
        if "ref" in desc:
            r = by_ordinal.get(desc["ref"] & 0x7FFF)
            base = r["name"] if r else f"class#{desc['ref'] & 0x7FFF}"
        if mod == 0x00:
            return base
        if mod in (0x01, 0x02, 0x03):
            return "T*"                       # untyped pointer (no static class)
        if mod == 0x10:
            return f"{base}[{desc.get('count')}]"
        if mod == 0x11:
            return f"T*[{desc.get('count')}]"
        if mod == 0x50:
            return f"container< {base} >"
        if mod == 0x51:
            return "container< T* >"
        return f"{base} <mod{mod:02x}>"
    if kind == 0x0d:
        inner = type_string(desc["inner"], by_ordinal) if "inner" in desc else "?"
        if mod == 0x10:
            return f"{inner} [x{desc.get('count')}]"
        return f"container< {inner} >"
    name = KIND_NAMES.get(kind, f"kind{kind:02x}")
    if mod == 0x00:
        return name
    if mod == 0x10:
        return f"{name}[{desc.get('count')}]"
    if mod == 0x50:
        return f"container< {name} >"
    if mod == 0x60:
        return name                       # AString always carries mod 0x60
    return f"{name} <mod{mod:02x}>"


def split_template_args(s: str):
    """Split top-level template arguments: 'A, std::pair< B, C >' -> [A, pair]."""
    out, depth, cur = [], 0, []
    for ch in s:
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        if ch == "," and depth == 0:
            out.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        out.append("".join(cur).strip())
    return out


def pair_ground_truth(records):
    """Ground-truth scalar tags from synthetic std::pair< A, B > classes.

    The class name spells the C++ types of fields `first`/`second`, so the
    descriptor tags of those fields calibrate the codebook with no outside
    knowledge.  Returns {cpp_type: Counter(tag_hex)}.
    """
    gt = defaultdict(Counter)
    for r in records:
        n = r["name"]
        if not (n.startswith("std::pair<") and n.endswith(">")):
            continue
        if len(r.get("fields", [])) != 2:
            continue
        args = split_template_args(n[len("std::pair<"):-1].strip())
        if len(args) != 2:
            continue
        for arg, fld in zip(args, r["fields"]):
            gt[arg][fld["desc"]["tag_hex"]] += 1
    return gt


def harvest_identifiers(data: bytes, clean_end: int):
    """Harvest every length-prefixed identifier candidate (task step 1).

    Two prefix widths occur: u16 (class names / synthetic type strings) and
    u32 (field names).  Classify each and report region (clean vs degraded).
    """
    n = len(data)
    charset = set(b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_:<>*&,~ ")
    found = []
    i = 2
    while i < n:
        # u32-prefixed (field names, always m_/plain identifiers)
        L4 = struct.unpack_from("<I", data, i - 4)[0] if i >= 4 else 0
        L2 = struct.unpack_from("<H", data, i - 2)[0]
        taken = False
        for width, L in ((4, L4), (2, L2)):
            if 3 <= L <= 200 and i + L <= n:
                s = data[i:i + L]
                if s[0:1].isalpha() and all(c in charset for c in s) and \
                        (i + L >= n or data[i + L] not in charset or True):
                    found.append({"offset": i, "prefix": width, "text": s.decode("latin1")})
                    i += L
                    taken = True
                    break
        if not taken:
            i += 1
    for f in found:
        t = f["text"]
        if t.startswith("m_"):
            cls = "field_name"
        elif t.startswith("std::") or t in ("ElementId", "unsigned int", "unsigned long",
                                           "int", "double", "bool", "AString") or "<" in t:
            cls = "type_string"
        elif re.match(r"^[A-Z][A-Za-z0-9_]+$", t) and any(c.islower() for c in t):
            cls = "class_or_camel_name"
        elif re.match(r"^[a-z][A-Za-z0-9_]+$", t):
            cls = "lower_ident"
        else:
            cls = "other"
        f["class"] = cls
        f["region"] = "clean" if f["offset"] < clean_end else "degraded"
    return found


def salvage_degraded_headers(data: bytes, start: int):
    """In the degraded region, resync on plausible class-record headers
    (u16 0000, u16 len, mostly-printable name, sane base/version/fieldcount).
    These are UNTRUSTED; many are LZ-duplicated copies of clean records."""
    out = []
    n = len(data)
    for i in range(start, n - 40):
        if data[i] or data[i + 1]:
            continue
        L = data[i + 2] | (data[i + 3] << 8)
        if not 4 <= L <= 64 or i + 4 + L + 10 > n:
            continue
        name = data[i + 4:i + 4 + L]
        if not name[0:1].isalpha():
            continue
        printable = sum(1 for c in name if 32 <= c < 127)
        if printable < 0.75 * L:
            continue
        j = i + 4 + L
        base = data[j] | (data[j + 1] << 8)
        version = struct.unpack_from("<I", data, j + 2)[0]
        fc = struct.unpack_from("<I", data, j + 6)[0]
        if version < 4000 and fc < 200 and (base == 0 or (base & 0x8000) or base < 6000):
            out.append({"offset": i, "name": name.decode("latin1"), "base_ref": base,
                        "version": version, "field_count": fc})
    return out


def degradation_profile(data: bytes, window: int = 8192):
    """Density of well-formed u32-prefixed m_ field names per window — the
    statistic that locates the faithful/degraded boundary."""
    ident = re.compile(rb"[A-Za-z_][A-Za-z0-9_]*$")
    n = len(data)
    prof = [0] * ((n // window) + 1)
    i = 4
    while i < n:
        L = struct.unpack_from("<I", data, i - 4)[0]
        if 4 <= L <= 60 and i + L <= n and data[i:i + 2] == b"m_" and ident.match(data[i:i + L]):
            prof[i // window] += 1
            i += L
            continue
        i += 1
    return prof


# ---------------------------------------------------------------------------
# build + emit
# ---------------------------------------------------------------------------

def load_stream(path: str = DEFAULT_STREAM) -> bytes:
    with open(path, "rb") as f:
        return f.read()


def build(path: str = DEFAULT_STREAM) -> dict:
    data = load_stream(path)
    parser = SchemaParser(data)
    clean_end, err = parser.parse()
    recs = parser.records
    by_ord = parser.by_ordinal

    # ordinal verification: every flagged inline reference must equal the
    # ordinal we independently assigned by definition order.
    ordinal_mismatches = [
        {"ordinal": r["ordinal"], "expected": r["expect"], "name": r["name"]}
        for r in recs if r["expect"] is not None and r["expect"] != r["ordinal"]
    ]

    # per-class output
    classes = []
    tag_counter = Counter()
    tag_examples = defaultdict(list)
    field_type_counter = Counter()
    inherit_edges = []
    ref_counter = Counter()
    for r in recs:
        fields_out = []
        for f in r.get("fields", []):
            d = f["desc"]
            ts = type_string(d, by_ord)
            tag_counter[d["tag_hex"]] += 1
            field_type_counter[ts] += 1
            if len(tag_examples[d["tag_hex"]]) < 4:
                tag_examples[d["tag_hex"]].append(f"{r['name']}.{f['name']}")
            fo = {"name": f["name"], "tag_hex": d["tag_hex"], "type_string": ts,
                  "offset": d["off"]}
            for k in ("ref", "count", "ref2", "k", "sep"):
                if k in d:
                    fo[k] = d[k]
            if "ref" in d:
                target = by_ord.get(d["ref"] & 0x7FFF)
                fo["ref_class"] = target["name"] if target else None
                fo["ref_inline_def"] = bool(d["ref"] & 0x8000)
                if target:
                    ref_counter[target["name"]] += 1
            fields_out.append(fo)
        base_ord = r["base_ref"] & 0x7FFF if r["base_ref"] else None
        base_name = by_ord[base_ord]["name"] if base_ord in by_ord else None
        if base_ord is not None:
            inherit_edges.append((r["name"], base_name or f"class#{base_ord}"))
        classes.append({
            "ordinal": r["ordinal"],
            "class_name": r["name"],
            "offset": r["offset"],
            "end": r.get("end"),
            "depth": r["depth"],
            "base_ordinal": base_ord,
            "base_name": base_name,
            "base_inline_def": bool(r["base_ref"] & 0x8000) if r["base_ref"] else False,
            "version": r.get("version"),
            "field_count": len(r.get("fields", [])),
            "fields": fields_out,
            "trailer_guid_count": len(r.get("trailer_guids", [])),
            "trailer_guids": r.get("trailer_guids", []),
        })

    # coverage: top-level (depth-0) records tile [0, clean_end) exactly
    top = [c for c in classes if c["depth"] == 0]
    tiles_ok = True
    covered = 0
    prev_end = 0
    for c in top:
        if c["offset"] != prev_end:
            tiles_ok = False
        covered += (c["end"] - c["offset"])
        prev_end = c["end"]
    coverage = {
        "stream_size": len(data),
        "clean_end": clean_end,
        "clean_fraction": round(clean_end / len(data), 4),
        "top_level_records_tile_clean_region": tiles_ok and prev_end == clean_end,
        "bytes_covered_by_records": covered,
        "degraded_bytes": len(data) - clean_end,
        "degraded_fraction": round((len(data) - clean_end) / len(data), 4),
        "stop_error": err,
    }

    # statistics / codebook
    gt = pair_ground_truth(recs)
    codebook = []
    for tag, cnt in tag_counter.most_common():
        kind = int(tag[0:2], 16)
        mod = int(tag[2:4], 16)
        codebook.append({
            "tag_hex": tag, "kind": KIND_NAMES.get(kind, "?"),
            "modifier": MOD_NAMES.get(mod, "?"), "count": cnt,
            "examples": tag_examples[tag],
        })
    stats = {
        "record_count": len(recs),
        "top_level_count": len(top),
        "inline_count": len(recs) - len(top),
        "field_count_total": sum(len(r.get("fields", [])) for r in recs),
        "ordinal_base": ORDINAL_BASE,
        "ordinal_last": recs[-1]["ordinal"] if recs else None,
        "ordinal_mismatch_count": len(ordinal_mismatches),
        "ordinal_mismatches": ordinal_mismatches[:20],
        "version_histogram": Counter(r.get("version") for r in recs).most_common(20),
        "most_common_field_types": field_type_counter.most_common(30),
        "most_referenced_classes": ref_counter.most_common(30),
        "inheritance_edge_count": len(inherit_edges),
        "root_class_count": sum(1 for c in classes if c["base_ordinal"] is None),
        "trailer_guid_classes": [(c["class_name"], c["trailer_guid_count"])
                                 for c in classes if c["trailer_guid_count"]],
        "pair_ground_truth": {k: dict(v) for k, v in sorted(gt.items())},
        "name_first_letter_top_level": Counter(c["class_name"][0] for c in top).most_common(),
    }

    idents = harvest_identifiers(data, clean_end)
    ident_summary = Counter((f["class"], f["region"]) for f in idents)
    salvage = salvage_degraded_headers(data, clean_end)
    salvage_names = Counter(s["name"] for s in salvage)
    prof = degradation_profile(data)

    # exhaustiveness check inside the faithful region: every u16-prefixed
    # A-CamelCase harvest hit must be a parsed record name.
    parsed_names_at = {c["offset"] + 4: c["class_name"] for c in classes}
    unaccounted = []
    for f in idents:
        if f["region"] != "clean" or f["prefix"] != 2:
            continue
        if f["class"] in ("class_or_camel_name", "type_string") and f["offset"] not in parsed_names_at:
            # could be a name embedded elsewhere; check it's inside some field/type
            unaccounted.append({"offset": f["offset"], "text": f["text"]})

    return {
        "stream": path,
        "sha256": hashlib.sha256(data).hexdigest(),
        "size": len(data),
        "method": "schema-b: structural/statistical (record-boundary alignment + gap statistics + pair<> ground truth)",
        "grammar": __doc__.split("Derived grammar")[1].split("Class ordinals")[0].strip(),
        "coverage": coverage,
        "stats": stats,
        "codebook": codebook,
        "classes": classes,
        "identifier_harvest_summary": [
            {"class": k[0], "region": k[1], "count": v} for k, v in ident_summary.most_common()],
        "clean_region_unaccounted_u16_identifiers": unaccounted[:50],
        "degraded_region": {
            "start": clean_end,
            "profile_window": 8192,
            "wellformed_field_density_per_window": prof,
            "salvaged_header_candidates_count": len(salvage),
            "salvaged_header_duplication_top": salvage_names.most_common(20),
            "salvaged_headers_sample": salvage[:40],
            "note": ("Content beyond clean_end is scrambled at write time by the "
                     "producer's compressor (see doc); records here are not "
                     "faithfully recoverable from this stream."),
        },
    }


def emit(path_out: str = OUT_JSON, path_in: str = DEFAULT_STREAM) -> dict:
    result = build(path_in)
    os.makedirs(os.path.dirname(path_out), exist_ok=True)
    with open(path_out, "w") as f:
        json.dump(result, f, indent=1)
    return result


# ---------------------------------------------------------------------------
# demo
# ---------------------------------------------------------------------------

def _print_summary(result: dict):
    cov = result["coverage"]
    st = result["stats"]
    print("=" * 78)
    print("schema-b : Formats/Latest structural/statistical decode")
    print("=" * 78)
    print(f"stream size            : {cov['stream_size']:,} bytes  sha256 {result['sha256'][:16]}...")
    print(f"faithful prefix end    : {cov['clean_end']:#x} ({cov['clean_fraction']*100:.1f}% of bytes)")
    print(f"records tile prefix    : {cov['top_level_records_tile_clean_region']}")
    print(f"stop reason            : {cov['stop_error']}")
    print(f"records parsed         : {st['record_count']} "
          f"(top-level {st['top_level_count']}, inline {st['inline_count']})")
    print(f"ordinals               : {st['ordinal_base']} .. {st['ordinal_last']} "
          f"(inline-def cross-check mismatches: {st['ordinal_mismatch_count']})")
    print(f"fields total           : {st['field_count_total']}")
    print(f"inheritance edges      : {st['inheritance_edge_count']}  roots: {st['root_class_count']}")
    print()
    print("-- type-tag codebook (tag -> count -> meaning -> examples)")
    for e in result["codebook"]:
        ex = ", ".join(e["examples"][:2])
        print(f"  {e['tag_hex']}  {e['count']:5d}  {e['kind']:>15} / {e['modifier']:<13} {ex}")
    print()
    print("-- pair<> ground truth (C++ type -> descriptor tags)")
    for k, v in st["pair_ground_truth"].items():
        if "<" in k or k[0].isupper() and k not in ("AString", "ElementId"):
            continue
        print(f"  {k:24} {v}")
    print()
    print("-- most common field types (rendered)")
    for t, c in st["most_common_field_types"][:12]:
        print(f"  {c:5d}  {t}")
    print()
    print("-- most referenced classes")
    for t, c in st["most_referenced_classes"][:10]:
        print(f"  {c:5d}  {t}")
    print()
    dr = result["degraded_region"]
    print("-- degraded region")
    print(f"  starts at {dr['start']:#x}; well-formed field density per 8 KiB window:")
    prof = dr["wellformed_field_density_per_window"]
    print("  " + " ".join(f"{v}" for v in prof[:24]) + " ...")
    print(f"  resynced header candidates: {dr['salvaged_header_candidates_count']}"
          f" (LZ-duplicated names, top: {dr['salvaged_header_duplication_top'][:3]})")
    print()
    print("-- first 12 classes")
    for c in result["classes"][:12]:
        base = f" : {c['base_name']}" if c["base_name"] else ""
        print(f"  {c['ordinal']:5d} @{c['offset']:#08x}  {c['class_name']}{base}  "
              f"(v{c['version']}, {c['field_count']} fields, {c['trailer_guid_count']} guids)")
        for f in c["fields"][:4]:
            print(f"           {f['tag_hex']}  {f['name']:28} {f['type_string']}")


def _cross_file_check():
    """Confirm the schema stream is byte-identical in all six samples."""
    shas = {}
    for s in SAMPLES:
        p = os.path.join(ROOT, "extracted", s, "Formats__Latest.gz", "000.bin")
        if os.path.exists(p):
            with open(p, "rb") as f:
                shas[s] = hashlib.sha256(f.read()).hexdigest()[:16]
    print("-- cross-file identity of Formats/Latest (inflated):")
    for s, h in shas.items():
        print(f"  {h}  {s}")
    print(f"  identical: {len(set(shas.values())) == 1}")


if __name__ == "__main__":
    stream = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_STREAM
    res = emit(OUT_JSON, stream)
    _print_summary(res)
    print()
    _cross_file_check()
    print()
    print(f"wrote {OUT_JSON}")
